/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import matematica.formularios_Temas;

/**
 *
 * @author User
 */
public class inicio extends javax.swing.JFrame {

    /**
     * Creates new form inicio
     */
    public inicio() {
        initComponents();
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        SetFondoPrin(jLabelMenuPrin,"src/imagen/fondoMenuPrin.jpg");
        SetFondoPrin(jLabelMundoMat,"src/imagen/planetaMate.png");
        SetFondoPrin(jLabelMundoHis,"src/imagen/planetaHistoria.png");
        SetFondoPrin(jLabelMundoAst,"src/imagen/planetaAstronomia.png");
        //botón mundo matemático
        jbtnMate.setOpaque(false);
        jbtnMate.setContentAreaFilled(false);
        jbtnMate.setBorderPainted(false);
        //botón mundo matemático
        jbtnHist.setOpaque(false);
        jbtnHist.setContentAreaFilled(false);
        jbtnHist.setBorderPainted(false);
        //botón mundo matemático
        jbtnAst.setOpaque(false);
        jbtnAst.setContentAreaFilled(false);
        jbtnAst.setBorderPainted(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMundoAst = new javax.swing.JLabel();
        jLabelMundoHis = new javax.swing.JLabel();
        jLabelMundoMat = new javax.swing.JLabel();
        jLabelMenuPrin = new javax.swing.JLabel();
        jbtnMate = new javax.swing.JButton();
        jbtnHist = new javax.swing.JButton();
        jbtnAst = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMundoAst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/planetaAstronomia.png"))); // NOI18N
        jPanel1.add(jLabelMundoAst, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 340, 300));

        jLabelMundoHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/planetaHistoria.png"))); // NOI18N
        jPanel1.add(jLabelMundoHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 320, 290));

        jLabelMundoMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/planetaMate.png"))); // NOI18N
        jPanel1.add(jLabelMundoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 320, 280));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoMenuPrin.jpg"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        jbtnMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 210, 140));

        jbtnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHistActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 210, 140));

        jbtnAst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAstActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAst, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 200, 130));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMateActionPerformed
        formularios_Temas conexMundoMate = new formularios_Temas();
        conexMundoMate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMateActionPerformed

    private void jbtnAstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAstActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnAstActionPerformed

    private void jbtnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnHistActionPerformed

    private void SetFondoPrin(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JLabel jLabelMundoAst;
    private javax.swing.JLabel jLabelMundoHis;
    private javax.swing.JLabel jLabelMundoMat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAst;
    private javax.swing.JButton jbtnHist;
    private javax.swing.JButton jbtnMate;
    // End of variables declaration//GEN-END:variables
}
