/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package formularios;

import Astronomia.formulario_TemasAstro;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import matematica.formularios_Temas;
import Historia.formulariosHis_Temas;

/**
 *
 * @author User
 */
public class inicio extends javax.swing.JFrame {
    
    public inicio() {
        initComponents();
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        SetFondoPrin(jLabelMenuPrin,"src/imagen/fondoMenuPrin.png");
        SetFondoPrin(jLabelMundoMat,"src/imagen/MundoMate.png");
        SetFondoPrin(jLabelMundoHis,"src/imagen/MundoHisto.png");
        SetFondoPrin(jLabelMundoAst,"src/imagen/MundoAstro.png");
        
        //botón mundo matemático
        jbtnMate.setOpaque(false);
        jbtnMate.setContentAreaFilled(false);
        jbtnMate.setBorderPainted(false);
        //botón mundo matemático
        jbtnHist.setOpaque(false);
        jbtnHist.setContentAreaFilled(false);
        jbtnHist.setBorderPainted(false);
        //botón mundo matemático
        jbtnAst.setOpaque(false);
        jbtnAst.setContentAreaFilled(false);
        jbtnAst.setBorderPainted(false);
        //botón ajustes
        jbtnAjuste.setOpaque(false);
        jbtnAjuste.setContentAreaFilled(false);
        jbtnAjuste.setBorderPainted(false);
        
        //animación para cada mundo
        aplicarEfectoPulso(jLabelMundoMat, jbtnMate,"/imagen/MundoMate.png");
        aplicarEfectoPulso(jLabelMundoHis, jbtnHist,"/imagen/MundoHisto.png");
        aplicarEfectoPulso(jLabelMundoAst, jbtnAst,"/imagen/MundoAstro.png");
        //efecto boton para el ajuste
        EfectoBoton(jbtnAjuste);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnAst = new javax.swing.JButton();
        jLabelMundoAst = new javax.swing.JLabel();
        jbtnHist = new javax.swing.JButton();
        jLabelMundoHis = new javax.swing.JLabel();
        jbtnMate = new javax.swing.JButton();
        jLabelMundoMat = new javax.swing.JLabel();
        jbtnAjuste = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnAst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAstActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAst, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 350, 170, 150));

        jLabelMundoAst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MundoAstro.png"))); // NOI18N
        jPanel1.add(jLabelMundoAst, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 310, 250, 230));

        jbtnHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHistActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 310, 210, 190));

        jLabelMundoHis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MundoHisto.png"))); // NOI18N
        jPanel1.add(jLabelMundoHis, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 270, 250));

        jbtnMate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnMateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnMate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 180, 160));

        jLabelMundoMat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MundoMate.png"))); // NOI18N
        jPanel1.add(jLabelMundoMat, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 240, 230));

        jbtnAjuste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnAjuste.png"))); // NOI18N
        jbtnAjuste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAjusteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAjuste, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 30, 100, 70));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoMenuPrin.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnMateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnMateActionPerformed
        formularios_Temas conexMundoMate = new formularios_Temas();
        conexMundoMate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnMateActionPerformed

    private void jbtnAstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAstActionPerformed
        Astronomia.formulario_TemasAstro conexMundoAstro = new formulario_TemasAstro();
        conexMundoAstro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnAstActionPerformed

    private void jbtnHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHistActionPerformed
        // TODO add your handling code here:
        formulariosHis_Temas conexMundoHist = new formulariosHis_Temas();
        conexMundoHist.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnHistActionPerformed

    private void jbtnAjusteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAjusteActionPerformed
       
    }//GEN-LAST:event_jbtnAjusteActionPerformed
    
    //método para ajustar una imagen a un jLabel
    private void SetFondoPrin(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }
    
    //método para incluir movimiento en las imágenes
    private void aplicarEfectoPulso(javax.swing.JLabel label, javax.swing.JButton boton, String rutaImagen) {
        java.net.URL urlImagen = getClass().getResource(rutaImagen);
        if (urlImagen == null) return; 

        ImageIcon imgOriginal = new ImageIcon(urlImagen);
        final int anchoBase = label.getWidth();
        final int altoBase = label.getHeight();

        javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoBase, altoBase, java.awt.Image.SCALE_DEFAULT));
        label.setIcon(iconoNormal);

        javax.swing.Timer timerPulso = new javax.swing.Timer(30, null);

        timerPulso.addActionListener(new java.awt.event.ActionListener() {
            private double angulo = 0;

            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                double factorZoom = 1.0 + ((Math.sin(angulo) + 1.0) / 3.5) * 0.06;
                int nuevoAncho = (int) (anchoBase * factorZoom);
                int nuevoAlto = (int) (altoBase * factorZoom);

                label.setIcon(new ImageIcon(imgOriginal.getImage().getScaledInstance(nuevoAncho, nuevoAlto, java.awt.Image.SCALE_DEFAULT)));
                angulo += 0.1; 
            }
        });

        // Creamos el detector de eventos que detiene y limpia el pulso
        java.awt.event.MouseAdapter detectorMouse = new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                timerPulso.stop();          // Detiene el latido
                label.setIcon(iconoNormal); // Regresa al tamaño original
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                timerPulso.start();         // Reanuda el latido al salir
            }
        };

        // 🔥 LA SOLUCIÓN: Le asignamos el detector a la imagen Y TAMBIÉN al botón que está al frente
        label.addMouseListener(detectorMouse);
        if (boton != null) {
            boton.addMouseListener(detectorMouse);
        }

        timerPulso.start();
    }
    
    //método para el efecto botón
    private void EfectoBoton(javax.swing.JButton boton) {
        if (boton.getIcon() == null) return;

        ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
        int anchoNormal = imgOriginal.getIconWidth();
        int altoNormal = imgOriginal.getIconHeight();

        // Calculamos las tres escalas:
        int anchoHover = (int) (anchoNormal * 1.08); // Un poco más grande (Hover)
        int altoHover = (int) (altoNormal * 1.08);

        int anchoClick = (int) (anchoNormal * 0.94); // Un poco más chico (Efecto hundido/presionado)
        int altoClick = (int) (altoNormal * 0.94);

        // Creamos los tres iconos escalados
        javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
        javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
        javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

        // Estética del botón
        boton.setContentAreaFilled(false);
        boton.setBorderPainted(false);
        boton.setFocusPainted(false);
        boton.setIcon(iconoNormal);

        // Control total de la ilusión de presión
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoHover); // Crece al pasar el mouse
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {
                // Si sueltas el click dentro del botón, vuelve al tamaño hover
                if (boton.getBounds().contains(e.getPoint())) {
                    boton.setIcon(iconoHover);
                } else {
                    boton.setIcon(iconoNormal);
                }
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JLabel jLabelMundoAst;
    private javax.swing.JLabel jLabelMundoHis;
    private javax.swing.JLabel jLabelMundoMat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAjuste;
    private javax.swing.JButton jbtnAst;
    private javax.swing.JButton jbtnHist;
    private javax.swing.JButton jbtnMate;
    // End of variables declaration//GEN-END:variables
}
