package formularios;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author sayuri
 */
import menu_p.*;
import javax.swing.ImageIcon;

public class menu extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(menu.class.getName());

    private javax.swing.Timer timerAnimacion;
    private int escalaActual = 0;
    private boolean agrandando = true;
    private final int X_BASE = 345;
    private final int Y_BASE = 320;
    private final int ANCHO_BASE = 180;
    private final int ALTO_BASE = 165;
    private final int MAX_VARIACION = 5;

    public menu() {
        initComponents();
        setLocationRelativeTo(null);
        btnJugar.setOpaque(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setBorderPainted(false);
        iniciarEfectoPulso();
        btnJugar.setFocusPainted(false);
    btnJugar.setBorder(javax.swing.BorderFactory.createEmptyBorder()); //

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnJugar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnJugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/plays-Photoroom (1) (4).png"))); // NOI18N
        btnJugar.setBorder(null);
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnJugar.addActionListener(this::btnJugarActionPerformed);
        getContentPane().add(btnJugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 250, 200));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo11.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 740));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJugarActionPerformed
        // TODO add your handling code here:
        // Pega estas tres líneas aquí:
        if (timerAnimacion != null) {
            timerAnimacion.stop();
        }

        inicio newframe = new inicio();
        newframe.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new menu().setVisible(true));
    }

    // Pega este método completo aquí
    private void iniciarEfectoPulso() {
        // Guardamos la imagen original del botón antes de empezar a animar
        java.awt.Image imagenOriginal = ((javax.swing.ImageIcon) btnJugar.getIcon()).getImage();

        timerAnimacion = new javax.swing.Timer(80, new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (agrandando) {
                    escalaActual++;
                    if (escalaActual >= MAX_VARIACION) {
                        agrandando = false;
                    }
                } else {
                    escalaActual--;
                    if (escalaActual <= 0) {
                        agrandando = true;
                    }
                }

                // Calculamos el nuevo tamaño del botón
                int nuevoAncho = ANCHO_BASE + (escalaActual * 2);
                int nuevoAlto = ALTO_BASE + (escalaActual * 2);

                // 1. Cambiamos el tamaño del contenedor del botón
                btnJugar.setBounds(
                        X_BASE - escalaActual,
                        Y_BASE - escalaActual,
                        nuevoAncho,
                        nuevoAlto
                );

                // 2. Redimensionamos la imagen para que se adapte al nuevo tamaño
                java.awt.Image imagenEscalada = imagenOriginal.getScaledInstance(nuevoAncho, nuevoAlto, java.awt.Image.SCALE_SMOOTH);
                btnJugar.setIcon(new javax.swing.ImageIcon(imagenEscalada));
            }
        });
        timerAnimacion.start();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
