/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package matematica;

/**
 *
 * @author Usuario
 */
public class Conjunto1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Conjunto1.class.getName());

    /**
     * Creates new form Conjunto2
     */
    public Conjunto1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jBotonInterrogante = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/niños.Quiz.conjuntos(1) (1).png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/CanastaQuiz1 (2).png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 370, 190));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/flechaQUIZ1.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 470, 160, 130));

        jBotonInterrogante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BOTONQUIZ1 (1).png"))); // NOI18N
        jBotonInterrogante.setBorderPainted(false);
        jBotonInterrogante.setContentAreaFilled(false);
        jBotonInterrogante.addActionListener(this::jBotonInterroganteActionPerformed);
        getContentPane().add(jBotonInterrogante, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 630, -1, 80));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MENSAJEQUIZ1 (1).png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 590, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Quiz.Conjuntos (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBotonInterroganteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBotonInterroganteActionPerformed
      
        // 1. Creamos la instancia de la nueva pantalla de Evaluación
    Conjuntos2 ventanaEvaluacion = new Conjuntos2(); 
    
    // 2. La hacemos visible
    ventanaEvaluacion.setVisible(true); 
    
    // 3. La centramos en la pantalla
    ventanaEvaluacion.setLocationRelativeTo(null); 
    
    // 4. Cerramos la ventana actual de bienvenida
    this.dispose();
    }//GEN-LAST:event_jBotonInterroganteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Conjunto1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBotonInterrogante;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
