
package Astronomia;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class DefinicionSS extends javax.swing.JFrame {
    
    private AstronautaController astro;
    private AudioController audio;
    
    public DefinicionSS() {
        
        initComponents();
        
        astro = new AstronautaController(jlabelAstro);
        astro.iniciar();  
        
        audio = new AudioController();
        reproducirNarracion("DescubrimientoViaLac.wav");
        
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/VLfondoDes.png");
        //TRANSPARENCIA
        jbtnSig.setContentAreaFilled(false);
        jbtnSig.setBorderPainted(false);
        jbtnSig.setOpaque(false);
        
        jbtnAnt1.setContentAreaFilled(false);
        jbtnAnt1.setBorderPainted(false);
        jbtnAnt1.setOpaque(false);
        
        jbtnF1.setContentAreaFilled(false);
        jbtnF1.setBorderPainted(false);
        jbtnF1.setOpaque(false);
        
        jbtnF2.setContentAreaFilled(false);
        jbtnF2.setBorderPainted(false);
        jbtnF2.setOpaque(false);
       
        EfectoBoton(jbtnSig);
        EfectoBoton(jbtnAnt1);
        EfectoBoton(jbtnF1);
        EfectoBoton(jbtnF2);
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnF2 = new javax.swing.JButton();
        jbtnF1 = new javax.swing.JButton();
        jbtnSig = new javax.swing.JButton();
        jbtnAnt1 = new javax.swing.JButton();
        jlabelAstro = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnF2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/VLfase2.png"))); // NOI18N
        jbtnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnF2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 200, 370, 320));

        jbtnF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/VLfase1.png"))); // NOI18N
        jbtnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnF1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, 370, 320));

        jbtnSig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonNext1.png"))); // NOI18N
        jbtnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSigActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSig, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 250, 100));

        jbtnAnt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonAnterior.png"))); // NOI18N
        jbtnAnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnt1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 250, 100));

        jlabelAstro.setText("jLabel1");
        jPanel1.add(jlabelAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 420));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabelMenuPrin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/VLfondoDes.png"))); // NOI18N
        jLabelMenuPrin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 670));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        formulario_TemasAstro pantallaAstro = new formulario_TemasAstro();
        pantallaAstro.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnAnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnt1ActionPerformed
        OrigenViaLactea conex = new OrigenViaLactea();
        conex.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnAnt1ActionPerformed

    private void jbtnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSigActionPerformed
        EstructuraViaLactea conex = new EstructuraViaLactea();
        conex.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSigActionPerformed

    private void jbtnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnF1ActionPerformed

    private void jbtnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnF2ActionPerformed
    //función para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }    
    
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
    }
    
    public void reproducirNarracion(String archivo) {

        astro.empezarHablar();

        audio.reproducir("/audio/" + archivo, () -> {

            astro.dejarDeHablar();

        });

    }
    
    private void reproducirAudioBoton(String archivo) {

        audio.reproducir("/audio/" + archivo, null);

    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefinicionSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefinicionSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefinicionSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefinicionSS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DefinicionSS().setVisible(true);
        } // Variables declaration - do not modify
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAnt1;
    private javax.swing.JButton jbtnF1;
    private javax.swing.JButton jbtnF2;
    private javax.swing.JButton jbtnSig;
    private javax.swing.JLabel jlabelAstro;
    // End of variables declaration//GEN-END:variables
}
