
package Astronomia;

import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import javax.swing.Icon;
import javax.swing.JLabel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicButtonUI;
/**
 *
 * @author User
 */
public class DefinicionViaLactea extends javax.swing.JFrame {
    
    private AstronautaController astro;
    private AudioController audio;
    
    public DefinicionViaLactea() {
        
        initComponents();
        
        astro = new AstronautaController(jlabelAstro);
        astro.iniciar();  
        
        audio = new AudioController();
        reproducirNarracion("ViaLacteaDef.wav");
        
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/fondoDefinViaLac.png");
        //SetLabel(jlabelAstro, "src/imagen/normal.png");
        
        jbtnNext1.setContentAreaFilled(false);
        jbtnNext1.setBorderPainted(false);
        jbtnNext1.setOpaque(false);
        
        
        
        EfectoBoton(jbtnNext1);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabelAstro = new javax.swing.JLabel();
        jbtnNext1 = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelAstro.setText("jLabel1");
        jPanel1.add(jlabelAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 270, 420));

        jbtnNext1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonNext1.png"))); // NOI18N
        jbtnNext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNext1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 520, 240, 80));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 90));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoDefinViaLac.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        teoria_Origen pantallaOrigen = new teoria_Origen();
        pantallaOrigen.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnNext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNext1ActionPerformed
        // TODO add your handling code here:
        OrigenViaLactea conexion = new OrigenViaLactea();
        conexion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNext1ActionPerformed
    //función para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }    
    
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
    }
    
    private static class ParticulaCosmica {
        double x, y;
        double velX, velY;
        float opacidad = 1.0f;
        double tamano;
        Color colorResplandor;
        Color colorCentro;
        double friccion = 1; 

        ParticulaCosmica(double x, double y, double angulo, java.util.Random random) {
            this.x = x;
            this.y = y;

            // Velocidad de la explosión cósmica
            double velocidad = 3.0 + random.nextDouble() * 6.0; // Cambiamos el (3.0 y 6.0) por más potencia
            this.velX = Math.cos(angulo) * velocidad;
            this.velY = Math.sin(angulo) * velocidad;

            // Tamaño de los destellos luminosos
            this.tamano = 3.0 + random.nextDouble() * 5.0; 

            // CONFIGURACIÓN DE ILUMINACIÓN DE TU IMAGEN (Núcleo brillante + Resplandor de luz)
            int probabilidad = random.nextInt(100);
            if (probabilidad < 75) {
                // Estrellas doradas hiper-iluminadas (Como tu guirnalda)
                this.colorResplandor = new Color(255, 170, 0, 180); // Aura naranja/oro traslúcida
                this.colorCentro = new Color(255, 255, 200);        // Centro amarillo/blanco brillante
            } else {
                // Destellos de energía pura blanca
                this.colorResplandor = new Color(255, 230, 130, 150); // Aura amarilla suave
                this.colorCentro = Color.WHITE;                       // Núcleo blanco incandescente
            }
        }

        void actualizar() {
            velX *= friccion;
            velY *= friccion;
            x += velX;
            y += velY;

            opacidad -= 0.025f; 
            if (opacidad < 0) opacidad = 0;
        }

        // Dibuja el efecto de iluminación real (Glow Effect)
        void dibujar(Graphics2D g2d) {
            // Ajustamos la opacidad general de la partícula según su tiempo de vida
            g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, opacidad));

            // 1. DIBUJAR EL RESPLANDOR (Círculo difuminado externo más grande)
            g2d.setColor(colorResplandor);
            double tamanoGlow = tamano * 2.2; // El aura es más del doble de grande
            g2d.fill(new java.awt.geom.Ellipse2D.Double(x - tamanoGlow/2.0, y - tamanoGlow/2.0, tamanoGlow, tamanoGlow));

            // 2. DIBUJAR EL NÚCLEO ENCIENDIDO (Círculo central brillante)
            g2d.setColor(colorCentro);
            g2d.fill(new java.awt.geom.Ellipse2D.Double(x - tamano/2.0, y - tamano/2.0, tamano, tamano));
        }
    }

// =========================================================================
// 2. MÉTODO PRINCIPAL: REUTILIZABLE PARA EL EFECTO BIG BANG
// =========================================================================
    private void activarBigBangEnBoton(JButton boton) {
        if (boton.getIcon() == null) return;

        boton.setOpaque(false);
        boton.setContentAreaFilled(false);
        boton.setBorderPainted(false);
        boton.setFocusPainted(false);
        boton.setBackground(new java.awt.Color(0, 0, 0, 0));

        final boolean[] mouseEncima = {false};
        final float[] progresoEstrella = {0.0f};

        final java.util.List<Point> puntosContorno = new ArrayList<>();
        final java.util.List<Double> angulosContorno = new ArrayList<>();
        final java.util.List<ParticulaCosmica> listaParticulas = new ArrayList<>();
        final Random random = new Random();

        final Timer timerAnimacion = new Timer(16, e -> {
            progresoEstrella[0] += 0.012f;
            if (progresoEstrella[0] > 1.0f) progresoEstrella[0] = 0.0f;

            if (mouseEncima[0] && !puntosContorno.isEmpty()) {
                int totalPuntos = puntosContorno.size();

                // Flujo constante de chispas de luz
                for (int k = 0; k < 5; k++) { 
                    int indiceAleatorio = random.nextInt(totalPuntos);
                    Point p = puntosContorno.get(indiceAleatorio);
                    double anguloDisparo = angulosContorno.get(indiceAleatorio);

                    anguloDisparo += (random.nextDouble() - 0.5) * 0.8;
                    listaParticulas.add(new ParticulaCosmica(p.x, p.y, anguloDisparo, random));
                }
            }

            Iterator<ParticulaCosmica> iter = listaParticulas.iterator();
            while (iter.hasNext()) {
                ParticulaCosmica p = iter.next();
                p.actualizar();
                if (p.opacidad <= 0) {
                    iter.remove();
                }
            }

            boton.repaint();
        });

        boton.setUI(new BasicButtonUI() {
            @Override
            public void paint(Graphics g, javax.swing.JComponent c) {
                Graphics2D g2d = (Graphics2D) g.create();

                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setRenderingHint(RenderingHints.KEY_ALPHA_INTERPOLATION, RenderingHints.VALUE_ALPHA_INTERPOLATION_QUALITY);

                g2d.setComposite(AlphaComposite.Clear);
                g2d.fillRect(0, 0, c.getWidth(), c.getHeight());
                g2d.setComposite(AlphaComposite.SrcOver);

                // --- 1. RENDERIZAR PARTÍCULAS CON ILUMINACIÓN REAL ---
                for (ParticulaCosmica p : listaParticulas) {
                    p.dibujar(g2d); // Llama al nuevo método de doble capa de color
                }
                g2d.setComposite(AlphaComposite.SrcOver); 

                // --- 2. RENDERIZAR LA ESTRELLA GUÍA ORBITAL ---
                if (mouseEncima[0] && !puntosContorno.isEmpty()) {
                    int totalPuntos = puntosContorno.size();
                    int indiceActual = (int) (progresoEstrella[0] * (totalPuntos - 1));
                    Point puntoEstrella = puntosContorno.get(indiceActual);

                    // Corrección de NetBeans: Guardamos la transformación de forma nativa
                    java.awt.geom.AffineTransform oldTransform = g2d.getTransform();

                    g2d.translate(puntoEstrella.x, puntoEstrella.y);
                    g2d.rotate(progresoEstrella[0] * Math.PI * 8); 
                    g2d.setColor(new Color(255, 240, 150)); 

                    java.awt.geom.Path2D estrellaPath = new java.awt.geom.Path2D.Double();
                    double rExter = 7.0; 
                    double rInter = 3.0; 
                    estrellaPath.moveTo(0, -rExter);
                    for (int i = 1; i < 10; i++) {
                        double r = (i % 2 == 0) ? rExter : rInter;
                        double angulo = i * Math.PI / 5.0;
                        estrellaPath.lineTo(r * Math.sin(angulo), -r * Math.cos(angulo));
                    }
                    estrellaPath.closePath();
                    g2d.fill(estrellaPath);

                    g2d.setTransform(oldTransform); // Corrección de NetBeans: Restauramos
                }

                g2d.dispose();
                super.paint(g, c); 
            }
        });

        boton.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                mouseEncima[0] = true;

                if (puntosContorno.isEmpty()) {
                    int centroX = boton.getWidth() / 2;
                    int centroY = boton.getHeight() / 2;

                    // Radio circular exacto para rodear tu explosión de forma perfecta
                    int radioExplosion = 15; 

                    for (int i = 0; i < 360; i++) {
                        double anguloRad = Math.toRadians(i);
                        int x = centroX + (int) (Math.cos(anguloRad) * radioExplosion);
                        int y = centroY + (int) (Math.sin(anguloRad) * radioExplosion);

                        puntosContorno.add(new Point(x, y));
                        angulosContorno.add(anguloRad);
                    }
                }

                // ¡EL IMPACTO DEL BIG BANG INICIAL CON ILUMINACIÓN!
                if (!puntosContorno.isEmpty()) {
                    for (int i = 0; i < 30; i++) { 
                        int randIdx = random.nextInt(puntosContorno.size());
                        Point p = puntosContorno.get(randIdx);
                        double ang = angulosContorno.get(randIdx) + (random.nextDouble() - 0.5) * 0.8;
                        listaParticulas.add(new ParticulaCosmica(p.x, p.y, ang, random));
                    }
                }

                timerAnimacion.start();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mouseEncima[0] = false;
                Timer retrasoApagado = new Timer(800, ev -> {
                    if (!mouseEncima[0] && listaParticulas.isEmpty()) {
                        timerAnimacion.stop();
                    }
                });
                retrasoApagado.setRepeats(false);
                retrasoApagado.start();
            }
        });
    }
    
    public void reproducirNarracion(String archivo) {

        astro.empezarHablar();

        audio.reproducir("/audio/" + archivo, () -> {

            astro.dejarDeHablar();

        });

    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DefinicionViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DefinicionViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DefinicionViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DefinicionViaLactea.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new DefinicionViaLactea().setVisible(true);
        } // Variables declaration - do not modify
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnNext1;
    private javax.swing.JLabel jlabelAstro;
    // End of variables declaration//GEN-END:variables
}
