/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import formularios.*;
import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.Timer;


/**
 *
 * @author User
 */
public class formulario_TemasAstro extends javax.swing.JFrame {
    
    public formulario_TemasAstro() {
        initComponents();
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //imagen se adapte al label
        SetFondoPrin(jLabelFondoAstro, "src/imagen/fondoPrinAstro2.png");
        //imagen se adapte al botón
        /*SetBotones(jbtnOrigen, "src/imagen/btnOrigen.png");
        SetBotones(jbtnSistSolar, "src/imagen/btnSisSol.png");
        SetBotones(jbtnViaLact, "src/imagen/btnViaLac.png");
        SetBotones(jbtnPlaneta, "src/imagen/btnPlanetas.png");*/
        //EfectoBotonMaster
        EfectoBotonMaster(jbtnPlaneta);
        EfectoBotonMaster(jbtnOrigen);
        EfectoBotonMaster(jbtnSistSolar);
        EfectoBotonMaster(jbtnViaLact);
        //transparencia para el botón origen
        jbtnOrigen.setContentAreaFilled(false);
        jbtnOrigen.setBorderPainted(false);
        jbtnOrigen.setOpaque(false);
        //transparencia para el botón vía láctea
        jbtnSistSolar.setOpaque(false);
        jbtnSistSolar.setContentAreaFilled(false);
        jbtnSistSolar.setBorderPainted(false);
        //transparencia para el botón sistema solar
        jbtnViaLact.setContentAreaFilled(false);
        jbtnViaLact.setBorderPainted(false);
        jbtnViaLact.setOpaque(false);
        //transparencia para el botón sistema solar
        jbtnPlaneta.setContentAreaFilled(false);
        jbtnPlaneta.setBorderPainted(false);
        jbtnPlaneta.setOpaque(false);
        //efectos para los botones        
        EfectoBoton(jbtnOrigen);
        EfectoBoton(jbtnSistSolar);
        EfectoBoton(jbtnViaLact);
        EfectoBoton(jbtnPlaneta);
        
        
        //efecto boton para el ajuste
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnPlaneta = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        jbtnOrigen = new javax.swing.JButton();
        jbtnSistSolar = new javax.swing.JButton();
        jbtnViaLact = new javax.swing.JButton();
        jLabelFondoAstro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnPlaneta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnPlanetas.png"))); // NOI18N
        jbtnPlaneta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPlanetaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPlaneta, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 240, 230));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 90));

        jbtnOrigen.setBackground(new java.awt.Color(242, 242, 242));
        jbtnOrigen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnOrigen.png"))); // NOI18N
        jbtnOrigen.setBorderPainted(false);
        jbtnOrigen.setOpaque(true);
        jbtnOrigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrigenActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnOrigen, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 240, 220));

        jbtnSistSolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnSisSol.png"))); // NOI18N
        jbtnSistSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSistSolarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSistSolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 230, 220));

        jbtnViaLact.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnViaLac.png"))); // NOI18N
        jbtnViaLact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnViaLactActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnViaLact, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 230, 230));

        jLabelFondoAstro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoPrinAstro2.png"))); // NOI18N
        jPanel1.add(jLabelFondoAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOrigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrigenActionPerformed
        teoria_Origen conexOrigen = new teoria_Origen();
        conexOrigen.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnOrigenActionPerformed

    private void jbtnSistSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSistSolarActionPerformed
        teoria_SistSolar conexSistSolar = new teoria_SistSolar();
        conexSistSolar.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbtnSistSolarActionPerformed

    private void jbtnViaLactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnViaLactActionPerformed
        teoria_ViaLact conexViaLac = new teoria_ViaLact();
        conexViaLac.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnViaLactActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        inicio pantallaInicio = new inicio();
        pantallaInicio.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnPlanetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPlanetaActionPerformed
        teoria_Planetas conexPlanetas = new teoria_Planetas();
        conexPlanetas.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbtnPlanetaActionPerformed

    
    //método para ajustar una imagen a un jLabel
    private void SetFondoPrin(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }
    //método para ajustar una imagen a un botón
    /*private void SetBotones(JButton ButonName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(ButonName.getWidth(), ButonName.getHeight(), Image.SCALE_DEFAULT));
        ButonName.setIcon(icon);
        this.repaint();
    }*/
    
    //método para el efecto botón
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
        }
    
    private void EfectoBotonMaster(javax.swing.JButton boton) {
        if (boton.getIcon() == null) return;

        ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
        final int anchoNormal = imgOriginal.getIconWidth();
        final int altoNormal = imgOriginal.getIconHeight();

        javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));

        // Corrección para evitar cualquier tipo de cortada cuadrada
        boton.setOpaque(false);
        boton.setContentAreaFilled(false);
        boton.setBorderPainted(false);
        boton.setFocusPainted(false);
        boton.setBackground(new java.awt.Color(0, 0, 0, 0));
        boton.setIcon(iconoNormal);

        // Variable de control para saber si el mouse está encima
        final boolean[] mouseEncima = {false};

        // Inyectamos la sombra morada suave y transparente alrededor de todo el círculo
        boton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
            @Override
            public void paint(Graphics g, javax.swing.JComponent c) {
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
                g2d.setRenderingHint(RenderingHints.KEY_STROKE_CONTROL, RenderingHints.VALUE_STROKE_PURE);

                // Limpieza absoluta de la caja del botón para asegurar transparencia total
                g2d.setComposite(AlphaComposite.Clear);
                g2d.fillRect(0, 0, c.getWidth(), c.getHeight());
                g2d.setComposite(AlphaComposite.SrcOver);

                // DIBUJAR LUZ: Solo cuando el mouse está encima
                if (mouseEncima[0]) {
                    int centroX = c.getWidth() / 2;
                    int centroY = c.getHeight() / 2;

                    Color colorSombraMorada = new Color(170, 90, 255);

                    // Calcula el radio basándose en el tamaño original fijo
                    int radioBase = anchoNormal / 2; 

                    // 12 capas delgadas para que el halo cubra todo el contorno de forma suave
                    for (int i = 12; i >= 0; i--) {
                        g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, 0.05f));
                        g2d.setColor(colorSombraMorada);

                        int radioActual = radioBase + (int)(i * 1.2f); 
                        int esquinaX = centroX - radioActual;
                        int esquinaY = centroY - radioActual;
                        int diametro = radioActual * 2;

                        g2d.fillOval(esquinaX, esquinaY, diametro, diametro);
                    }
                }
                g2d.dispose();
                super.paint(g, c); // Dibuja la imagen por encima sin alterarla
            }
        });

        // Listeners del Mouse simplificados únicamente para controlar la luz
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                mouseEncima[0] = true;
                boton.repaint();
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                mouseEncima[0] = false;
                boton.repaint();
            }
        });
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formulario_TemasAstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formulario_TemasAstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formulario_TemasAstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formulario_TemasAstro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formulario_TemasAstro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelFondoAstro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnOrigen;
    private javax.swing.JButton jbtnPlaneta;
    private javax.swing.JButton jbtnSistSolar;
    private javax.swing.JButton jbtnViaLact;
    // End of variables declaration//GEN-END:variables
}
