/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Point;
import java.awt.Rectangle;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;
import java.util.List;
import java.util.Random;
import java.util.Set;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.Timer;
import javax.swing.border.LineBorder;

/**
 *
 * @author sayuri
 */
public class Nivel2Planetas1 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nivel2Planetas1.class.getName());

    private int numeroMision = 0;

    private Timer timerMovimiento;
    private final Random random = new Random();

    private JLabel lblPregunta;
    private JLabel lblPuntaje;
    private JLabel lblMensajeJuego;

    private final List<PlanetaNivel2> planetas = new ArrayList<>();
    private final List<MisionNivel2> misiones = new ArrayList<>();
    private final Set<String> planetasPendientes = new HashSet<>();
    private final Set<String> planetasSeleccionados = new HashSet<>();

    /**
     * Creates new form Nivel2Planetas
     */
    public Nivel2Planetas1() {
        initComponents();
        prepararJuegoNivel2();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMercurio = new javax.swing.JLabel();
        lblTierra = new javax.swing.JLabel();
        lblVenus = new javax.swing.JLabel();
        lblNeptuno = new javax.swing.JLabel();
        lblUrano = new javax.swing.JLabel();
        lblSaturno = new javax.swing.JLabel();
        lblJupiter = new javax.swing.JLabel();
        lblMarte = new javax.swing.JLabel();
        btnPista = new javax.swing.JButton();
        btnSiguienteNivel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMercurio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/MercurioA1 (1).png"))); // NOI18N
        lblMercurio.setFocusable(false);
        lblMercurio.setInheritsPopupMenu(false);
        getContentPane().add(lblMercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, 110, 100));

        lblTierra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/TierraA1 (1).png"))); // NOI18N
        getContentPane().add(lblTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, 120, 110));

        lblVenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/VenusA1 (1).png"))); // NOI18N
        lblVenus.setText("jLabel4");
        getContentPane().add(lblVenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 200, 110, 100));

        lblNeptuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/NeptunoA1 (1).png"))); // NOI18N
        getContentPane().add(lblNeptuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 420, 110, 110));

        lblUrano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/uranoA1 (1).png"))); // NOI18N
        lblUrano.setText("jLabel6");
        getContentPane().add(lblUrano, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 120, 90));

        lblSaturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/saturnoA (1).png"))); // NOI18N
        getContentPane().add(lblSaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 190, 120, 90));

        lblJupiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/jupiterA1 (1).png"))); // NOI18N
        lblJupiter.setText("jLabel8");
        getContentPane().add(lblJupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 380, 110, 100));

        lblMarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/marteA1 (2) (1).png"))); // NOI18N
        getContentPane().add(lblMarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 310, 120, 100));

        btnPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/bottonPistaN2-removebg-preview (1) (1).png"))); // NOI18N
        btnPista.setBorderPainted(false);
        btnPista.setContentAreaFilled(false);
        btnPista.addActionListener(this::btnPistaActionPerformed);
        getContentPane().add(btnPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 520, 120, 60));

        btnSiguienteNivel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BootonSiguiN2-removebg-preview (1).png"))); // NOI18N
        btnSiguienteNivel.setBorderPainted(false);
        btnSiguienteNivel.setContentAreaFilled(false);
        btnSiguienteNivel.addActionListener(this::btnSiguienteNivelActionPerformed);
        getContentPane().add(btnSiguienteNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 580, 150, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Nivel 2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSiguienteNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteNivelActionPerformed
        // TODO add your handling code here:
        Nivel3Ordenar nivel = new Nivel3Ordenar();
        nivel.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSiguienteNivelActionPerformed

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:
        usarPista();
    }//GEN-LAST:event_btnPistaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Nivel2Planetas1().setVisible(true));
    }

    private void prepararJuegoNivel2() {
        crearTextosDelJuego();
        crearListaDePlanetas();
        crearMisiones();
        activarClickEnPlanetas();
        mostrarMisionActual();
        iniciarMovimientoPlanetas();

        // El fondo debe quedar atras. Si tu fondo no se llama jLabel1, cambia jLabel1 por el nombre de tu fondo.
        getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);
    }

    private void crearTextosDelJuego() {
        lblPregunta = new JLabel("", SwingConstants.CENTER);
        lblPregunta.setFont(new Font("Arial", Font.BOLD, 23));
        lblPregunta.setForeground(new Color(190, 245, 255));
        getContentPane().add(lblPregunta, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 155, 320, 135));

        lblPuntaje = new JLabel("", SwingConstants.CENTER);
        lblPuntaje.setOpaque(true);
        lblPuntaje.setFont(new Font("Arial", Font.BOLD, 22));
        lblPuntaje.setForeground(Color.WHITE);
        lblPuntaje.setBackground(new Color(8, 30, 85));
        lblPuntaje.setBorder(new LineBorder(new Color(50, 210, 255), 2));
        getContentPane().add(lblPuntaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, 175, 45));

        lblMensajeJuego = new JLabel("", SwingConstants.CENTER);
        lblMensajeJuego.setFont(new Font("Arial", Font.BOLD, 20));
        lblMensajeJuego.setForeground(new Color(255, 235, 80));
        getContentPane().add(lblMensajeJuego, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, 820, 45));

        actualizarPuntaje();
    }

    private void crearListaDePlanetas() {
        planetas.add(new PlanetaNivel2("Mercurio", "rocoso", lblMercurio, 2, 2));
        planetas.add(new PlanetaNivel2("Venus", "rocoso", lblVenus, -2, 2));
        planetas.add(new PlanetaNivel2("Tierra", "rocoso", lblTierra, 2, -2));
        planetas.add(new PlanetaNivel2("Marte", "rocoso", lblMarte, -2, -2));

        planetas.add(new PlanetaNivel2("Jupiter", "gaseoso", lblJupiter, 2, -2));
        planetas.add(new PlanetaNivel2("Saturno", "gaseoso", lblSaturno, -2, 2));
        planetas.add(new PlanetaNivel2("Urano", "gaseoso", lblUrano, 2, 2));
        planetas.add(new PlanetaNivel2("Neptuno", "gaseoso", lblNeptuno, -2, -2));
    }

    private void crearMisiones() {
        misiones.add(new MisionNivel2(
                "Atrapa a Marte",
                "Pista: busca el planeta rojizo, pequeño y con crateres.",
                "Marte"
        ));

        misiones.add(new MisionNivel2(
                "Atrapa Venus",
                "Pista: busca un planeta muy brillante de color amarillo/anaranjado.",
                "Venus"
        ));

        misiones.add(new MisionNivel2(
                "Atrapa los planetas rocosos",
                "Pista: tienen superficie solida y estan en la zona interior del Sistema Solar.",
                "Mercurio", "Venus", "Tierra", "Marte"
        ));

        misiones.add(new MisionNivel2(
                "Atrapa los planetas gaseosos",
                "Pista: son grandes, no tienen suelo firme y estan mas lejos del Sol.",
                "Jupiter", "Saturno", "Urano", "Neptuno"
        ));

        misiones.add(new MisionNivel2(
                "Atrapa a la Tierra",
                "Pista: tiene oceanos azules, nubes y continentes verdes.",
                "Tierra"
        ));

        misiones.add(new MisionNivel2(
                "Atrapa a Saturno",
                "Pista: tiene anillos grandes alrededor.",
                "Saturno"
        ));
    }

    private void activarClickEnPlanetas() {
        for (PlanetaNivel2 planeta : planetas) {
            planeta.label.setCursor(new Cursor(Cursor.HAND_CURSOR));
            planeta.label.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    verificarPlaneta(planeta);
                }
            });
        }
    }

    private void iniciarMovimientoPlanetas() {
        timerMovimiento = new Timer(30, e -> {
            for (PlanetaNivel2 planeta : planetas) {
                planeta.mover();
            }
        });
        timerMovimiento.start();
    }

    private void verificarPlaneta(PlanetaNivel2 planeta) {
        MisionNivel2 mision = misiones.get(numeroMision);

        if (mision.esCorrecto(planeta.nombre)) {
            if (planetasSeleccionados.contains(planeta.nombre)) {
                lblMensajeJuego.setText("Ese planeta ya fue seleccionado.");
                return;
            }

            planetasSeleccionados.add(planeta.nombre);
            planetasPendientes.remove(planeta.nombre);
            planeta.label.setBorder(new LineBorder(Color.YELLOW, 3));
            explosionEstrellas(planeta.label);

            if (planetasPendientes.isEmpty()) {
                GameData.sumarPuntos();
                lblMensajeJuego.setText("Muy bien: +10 puntos");
                pasarASiguienteMision();
            } else {
                lblMensajeJuego.setText("Bien. Sigue buscando los planetas correctos.");
            }
        } else {
            GameData.restarPuntos();
            lblMensajeJuego.setText("Incorrecto: -3 puntos");
        }

        actualizarPuntaje();
    }

    private void pasarASiguienteMision() {
        numeroMision++;

        if (numeroMision >= misiones.size()) {
            numeroMision = 0;
            JOptionPane.showMessageDialog(this, "Completaste todas las misiones del Nivel 2.");
        }

        mostrarMisionActual();
    }

    private void mostrarMisionActual() {
        quitarBordesDePlanetas();

        MisionNivel2 mision = misiones.get(numeroMision);
        planetasPendientes.clear();
        planetasSeleccionados.clear();
        planetasPendientes.addAll(mision.respuestasCorrectas);

        lblPregunta.setText("<html><center>" + mision.pregunta + "</center></html>");
        actualizarPuntaje();
    }

    private void quitarBordesDePlanetas() {
        for (PlanetaNivel2 planeta : planetas) {
            planeta.label.setBorder(null);
        }
    }

    private void actualizarPuntaje() {
        lblPuntaje.setText("Puntos: " + GameData.puntos);
    }

    private void usarPista() {
        if (GameData.puntos <= 0) {
            lblMensajeJuego.setText("Gastaste todos tus puntos");
            actualizarPuntaje();
            return;
        }
        GameData.restarPuntos();
        lblMensajeJuego.setText(misiones.get(numeroMision).pista);
        actualizarPuntaje();
    }

    /*private void irSiguienteNivel() {
    JOptionPane.showMessageDialog(this, "Aqui abres tu formulario del Nivel 3.");

 
}*/
    private void explosionEstrellas(JLabel planeta) {
        int centroX = planeta.getX() + planeta.getWidth() / 2;
        int centroY = planeta.getY() + planeta.getHeight() / 2;

        for (int i = 0; i < 8; i++) {
            JLabel estrella = new JLabel("*");
            estrella.setFont(new Font("Arial", Font.BOLD, 28));
            estrella.setForeground(Color.YELLOW);

            int x = centroX - 10 + random.nextInt(60) - 30;
            int y = centroY - 10 + random.nextInt(60) - 30;
            getContentPane().add(estrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, 30, 30));
            getContentPane().setComponentZOrder(estrella, 0);

            Timer borrar = new Timer(600, e -> {
                getContentPane().remove(estrella);
                getContentPane().repaint();
            });
            borrar.setRepeats(false);
            borrar.start();
        }

        getContentPane().repaint();
    }

    private class PlanetaNivel2 {

        String nombre;
        String tipo;
        JLabel label;
        int dx;
        int dy;

        PlanetaNivel2(String nombre, String tipo, JLabel label, int dx, int dy) {
            this.nombre = nombre;
            this.tipo = tipo;
            this.label = label;
            this.dx = dx;
            this.dy = dy;
        }

        void mover() {
            int nuevoX = label.getX() + dx;
            int nuevoY = label.getY() + dy;

            int limiteIzquierdo = 20;
            int limiteDerecho = getContentPane().getWidth() - label.getWidth() - 20;
            int limiteArriba = 145;
            int limiteAbajo = getContentPane().getHeight() - label.getHeight() - 85;

            if (nuevoX <= limiteIzquierdo || nuevoX >= limiteDerecho) {
                dx = dx * -1;
            }

            if (nuevoY <= limiteArriba || nuevoY >= limiteAbajo) {
                dy = dy * -1;
            }

            // Zona prohibida: caja donde esta el texto de MISION.
            // Ajusta estos numeros si tu panel de mision esta en otra posicion.
            Rectangle zonaMision = new Rectangle(45, 45, 400, 200);
            Rectangle futuroPlaneta = new Rectangle(nuevoX, nuevoY, label.getWidth(), label.getHeight());

            if (futuroPlaneta.intersects(zonaMision)) {
                dx = dx * -1;
                dy = dy * -1;
                nuevoX = label.getX() + dx;
                nuevoY = label.getY() + dy;
            }

            label.setLocation(label.getX() + dx, label.getY() + dy);
        }
    }

    private static class MisionNivel2 {

        String pregunta;
        String pista;
        Set<String> respuestasCorrectas;

        MisionNivel2(String pregunta, String pista, String... respuestas) {
            this.pregunta = pregunta;
            this.pista = pista;
            this.respuestasCorrectas = new HashSet<>(Arrays.asList(respuestas));
        }

        boolean esCorrecto(String nombrePlaneta) {
            return respuestasCorrectas.contains(nombrePlaneta);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPista;
    private javax.swing.JButton btnSiguienteNivel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJupiter;
    private javax.swing.JLabel lblMarte;
    private javax.swing.JLabel lblMercurio;
    private javax.swing.JLabel lblNeptuno;
    private javax.swing.JLabel lblSaturno;
    private javax.swing.JLabel lblTierra;
    private javax.swing.JLabel lblUrano;
    private javax.swing.JLabel lblVenus;
    // End of variables declaration//GEN-END:variables
}
