/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import javax.swing.Timer;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author sayuri
 */
public class Nivel1Sistemasolaryplaneta extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nivel1Sistemasolaryplaneta.class.getName());

    private Timer timer;

    private ArrayList<JLabel> planetas = new ArrayList<>();

    private ArrayList<Boolean> colocados = new ArrayList<>();

    private int xMouse;
    private int yMouse;
    private boolean arrastrando = false;
    private JLabel planetaArrastrado = null;
    private JLabel lblPuntos = new JLabel();
    private JLabel lblMercurioFijo = new JLabel();
    private JLabel lblVenusFijo = new JLabel();
    private JLabel lblTierraFijo = new JLabel();
    private JLabel lblMarteFijo = new JLabel();
    private JLabel lblJupiterFijo = new JLabel();
    private JLabel lblSaturnoFijo = new JLabel();
    private JLabel lblUranoFijo = new JLabel();
    private JLabel lblNeptunoFijo = new JLabel();
    private final int PANEL_X = 1120;
    private final int PANEL_Y_INICIO = 120;
    private final int PANEL_Y_FIN = 610;

    /**
     * Creates new form Sistemasolaryplaneta
     */
    public Nivel1Sistemasolaryplaneta() {
        initComponents();
        configurarContadorPuntos();

        cargarPlanetas();

        moverPlanetas();

        habilitarArrastre(lblMercurio);
        habilitarArrastre(lblVenus);
        habilitarArrastre(lblTierra);
        habilitarArrastre(lblMarte);
        habilitarArrastre(lblJupiter);
        habilitarArrastre(lblSaturno);
        habilitarArrastre(lblUrano);
        habilitarArrastre(lblNeptuno);

        getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);

        getContentPane().setComponentZOrder(lblMercurio, 0);
        getContentPane().setComponentZOrder(lblVenus, 0);
        getContentPane().setComponentZOrder(lblTierra, 0);
        getContentPane().setComponentZOrder(lblMarte, 0);
        getContentPane().setComponentZOrder(lblJupiter, 0);
        getContentPane().setComponentZOrder(lblSaturno, 0);
        getContentPane().setComponentZOrder(lblUrano, 0);
        getContentPane().setComponentZOrder(lblNeptuno, 0);

        // Ocultar los planetas del sistema solar
        lblLugarMercurio.setIcon(null);
        lblLugarVenus.setIcon(null);
        lblLugarTierra.setIcon(null);
        lblLugarMarte.setIcon(null);
        lblLugarJupiter.setIcon(null);
        lblLugarSaturno.setIcon(null);
        lblLugarUrano.setIcon(null);
        lblLugarNeptuno.setIcon(null);
        repaint();

        System.out.println(this);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLugarMercurio = new javax.swing.JLabel();
        lblLugarVenus = new javax.swing.JLabel();
        lblLugarMarte = new javax.swing.JLabel();
        lblLugarSaturno = new javax.swing.JLabel();
        lblLugarNeptuno = new javax.swing.JLabel();
        lblLugarUrano = new javax.swing.JLabel();
        lblLugarJupiter = new javax.swing.JLabel();
        lblLugarTierra = new javax.swing.JLabel();
        lblMercurio = new javax.swing.JLabel();
        lblVenus = new javax.swing.JLabel();
        lblTierra = new javax.swing.JLabel();
        lblMarte = new javax.swing.JLabel();
        lblJupiter = new javax.swing.JLabel();
        lblSaturno = new javax.swing.JLabel();
        lblUrano = new javax.swing.JLabel();
        lblNeptuno = new javax.swing.JLabel();
        btnPista = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lblLugarMercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, 70, 70));
        getContentPane().add(lblLugarVenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, 60));
        getContentPane().add(lblLugarMarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, 70, 60));
        getContentPane().add(lblLugarSaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 510, 70, 50));
        getContentPane().add(lblLugarNeptuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, 80, 60));
        getContentPane().add(lblLugarUrano, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 510, 80, 50));
        getContentPane().add(lblLugarJupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 350, 70, 60));
        getContentPane().add(lblLugarTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 70, 70));

        lblMercurio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Mercurio-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lblMercurio, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 150, 70, 60));

        lblVenus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Venus-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblVenus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 210, -1, -1));

        lblTierra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Tierra-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lblTierra, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 280, 70, 60));

        lblMarte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Marte-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lblMarte, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 70, 60));

        lblJupiter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/jupiter-removebg-preview (2).png"))); // NOI18N
        getContentPane().add(lblJupiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 410, 70, 60));

        lblSaturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Saturno-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblSaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 460, -1, -1));

        lblUrano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/urano-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblUrano, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 510, -1, -1));

        lblNeptuno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Neptuno-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblNeptuno, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 570, 70, 60));

        btnPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton_pista-removebg-preview (1).png"))); // NOI18N
        btnPista.setBorder(null);
        btnPista.setBorderPainted(false);
        btnPista.setContentAreaFilled(false);
        btnPista.addActionListener(this::btnPistaActionPerformed);
        getContentPane().add(btnPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 640, 120, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/BOTTONS1.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 180, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nivel 1 (6).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:
        if ( + GameData.puntos <= 0) {
            mostrarVentanaBonita("Sin puntos", "Gastaste todos tus puntos", "Total: 0 puntos");
            return;
        }

        restarPuntos(3);

        String[] pistas = {
            "Los planetas rocosos van antes que los gigantes gaseosos.",
            "La Tierra esta despues de Venus y antes de Marte.",
            "Los planetas mas lejanos son frios y estan despues de Saturno."
        };

        int numero = (int) (Math.random() * pistas.length);

        mostrarVentanaBonita(
                "Pista",
                pistas[numero],
                "-3 puntos | Total: "  + GameData.puntos
        );
    }//GEN-LAST:event_btnPistaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        Nivel2Planetas1 nivel2 = new Nivel2Planetas1();
        nivel2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Nivel1Sistemasolaryplaneta().setVisible(true));
    }

    private void configurarContadorPuntos() {
        lblPuntos.setOpaque(true);
        lblPuntos.setBackground(new Color(25, 35, 70));
        lblPuntos.setForeground(Color.WHITE);
        lblPuntos.setFont(new Font("Arial", Font.BOLD, 20));
        lblPuntos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPuntos.setBorder(BorderFactory.createLineBorder(new Color(255, 202, 40), 2));

        actualizarPuntos();

        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 180, 40));
        getContentPane().setComponentZOrder(lblPuntos, 0);
    }

    private void actualizarPuntos() {
        lblPuntos.setText("Puntos: " + GameData.puntos);
    }

  private void sumarPuntos(int cantidad) {
    GameData.sumarPuntos();
    actualizarPuntos();
}

private void restarPuntos(int cantidad) {
    GameData.restarPuntos();
    actualizarPuntos();

    if (GameData.puntos == 0) {
        mostrarVentanaBonita("Sin puntos", "Gastaste todos tus puntos", "Total: 0 puntos");
    }
}

    private void mostrarVentanaBonita(String titulo, String mensaje, String detalle) {
        JPanel panel = new JPanel(null);
        panel.setPreferredSize(new java.awt.Dimension(480, 260));
        panel.setBackground(new Color(28, 8, 75));
        panel.setBorder(BorderFactory.createLineBorder(new Color(45, 210, 255), 3));

        JLabel icono = new JLabel(titulo.equals("bien") ? "*" : "!");
        icono.setFont(new Font("Arial", Font.BOLD, 34));
        icono.setForeground(new Color(255, 235, 65));
        icono.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        icono.setBounds(25, 15, 55, 55);
        panel.add(icono);

        JLabel lblTitulo = new JLabel(titulo);
        lblTitulo.setOpaque(true);
        lblTitulo.setBackground(titulo.contains("bien") ? new Color(48, 86, 145) : new Color(105, 45, 85));
        lblTitulo.setForeground(new Color(255, 235, 65));
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 28));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setBounds(25, 18, 430, 52);
        panel.add(lblTitulo);

        JLabel lblMensaje = new JLabel(
                "<html><div style='width:390px;'>"
                + mensaje + "<br>"
                + detalle
                + "</div></html>"
        );
        lblMensaje.setOpaque(true);
        lblMensaje.setBackground(new Color(10, 30, 85));
        lblMensaje.setForeground(Color.WHITE);
        lblMensaje.setFont(new Font("Arial", Font.BOLD, 19));
        lblMensaje.setBorder(BorderFactory.createLineBorder(titulo.contains("bien") ? new Color(45, 210, 255) : new Color(255, 85, 75), 2));
        lblMensaje.setBounds(50, 95, 390, 95);
        panel.add(lblMensaje);

        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setBackground(titulo.contains("bien") ? new Color(45, 145, 245) : new Color(255, 85, 85));
        btnAceptar.setForeground(Color.WHITE);
        btnAceptar.setFont(new Font("Arial", Font.BOLD, 16));
        btnAceptar.setFocusPainted(false);
        btnAceptar.setBorder(BorderFactory.createLineBorder(new Color(255, 235, 65), 2));
        btnAceptar.setBounds(160, 225, 160, 45);
        panel.add(btnAceptar);

        javax.swing.JDialog dialogo = new javax.swing.JDialog(this, true);
        dialogo.setUndecorated(true);
        dialogo.getContentPane().add(panel);
        dialogo.pack();
        dialogo.setLocationRelativeTo(this);

        btnAceptar.addActionListener(e -> dialogo.dispose());

        dialogo.setVisible(true);
    }

    private void cargarPlanetas() {

        planetas.add(lblMercurio);
        planetas.add(lblVenus);
        planetas.add(lblTierra);
        planetas.add(lblMarte);
        planetas.add(lblJupiter);
        planetas.add(lblSaturno);
        planetas.add(lblUrano);
        planetas.add(lblNeptuno);

        for (int i = 0; i < planetas.size(); i++) {

            colocados.add(false);

        }
        lblMercurio.setLocation(PANEL_X, 100);
        lblVenus.setLocation(PANEL_X, 180);
        lblTierra.setLocation(PANEL_X, 260);
        lblMarte.setLocation(PANEL_X, 340);
        lblJupiter.setLocation(PANEL_X, 420);

        lblSaturno.setLocation(PANEL_X, 490);
        lblUrano.setLocation(PANEL_X, 600);

        lblNeptuno.setLocation(PANEL_X, 680);
    }

    private void moverPlanetas() {

        timer = new Timer(30, e -> {

            for (int i = 0; i < planetas.size(); i++) {

                JLabel planeta = planetas.get(i);

                if (colocados.get(i)) {
                    continue;
                }

                if (planeta == planetaArrastrado) {
                    continue;
                }

                planeta.setLocation(
                        planeta.getX(),
                        planeta.getY() + 1
                );

                if (planeta.getY() >= PANEL_Y_FIN) {

                    planeta.setLocation(
                            PANEL_X,
                            PANEL_Y_INICIO + 5
                    );

                }
            }

        });

        timer.start();

    }

    private void habilitarArrastre(JLabel planeta) {

        planeta.addMouseListener(new java.awt.event.MouseAdapter() {

            @Override
            public void mousePressed(MouseEvent evt) {

                xMouse = evt.getX();
                yMouse = evt.getY();
                arrastrando = true;
                planetaArrastrado = planeta;
            }

            @Override
            public void mouseReleased(MouseEvent evt) {

                timer.stop();

                verificarPosicion(planeta);

                planetaArrastrado = null;
                arrastrando = false;

                timer.start();
            }

        });

        planeta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {

            @Override
            public void mouseDragged(MouseEvent evt) {

                planeta.setLocation(
                        planeta.getX() + evt.getX() - xMouse,
                        planeta.getY() + evt.getY() - yMouse
                );

            }

        });

    }

    private void verificarPosicion(JLabel planeta) {

        JLabel lugar = null;

        if (planeta == lblMercurio) {
            lugar = lblLugarMercurio;
        } else if (planeta == lblVenus) {
            lugar = lblLugarVenus;
        } else if (planeta == lblTierra) {
            lugar = lblLugarTierra;
        } else if (planeta == lblMarte) {
            lugar = lblLugarMarte;
        } else if (planeta == lblJupiter) {
            lugar = lblLugarJupiter;
        } else if (planeta == lblSaturno) {
            lugar = lblLugarSaturno;
        } else if (planeta == lblUrano) {
            lugar = lblLugarUrano;
        } else if (planeta == lblNeptuno) {
            lugar = lblLugarNeptuno;
        }

        if (lugar != null && planeta.getBounds().intersects(lugar.getBounds())) {

            int indice = planetas.indexOf(planeta);

            colocados.set(indice, true);

            for (var ml : planeta.getMouseListeners()) {
                planeta.removeMouseListener(ml);
            }

            for (var mm : planeta.getMouseMotionListeners()) {
                planeta.removeMouseMotionListener(mm);
            }

            if (planeta == lblMercurio) {

                lblLugarMercurio.setIcon(lblMercurio.getIcon());
                lblMercurio.setVisible(false);

            } else if (planeta == lblVenus) {

                lblLugarVenus.setIcon(lblVenus.getIcon());
                lblVenus.setVisible(false);

            } else if (planeta == lblTierra) {

                lblLugarTierra.setIcon(lblTierra.getIcon());
                lblTierra.setVisible(false);

            } else if (planeta == lblMarte) {

                lblLugarMarte.setIcon(lblMarte.getIcon());
                lblMarte.setVisible(false);

            } else if (planeta == lblJupiter) {

                lblLugarJupiter.setIcon(lblJupiter.getIcon());
                lblJupiter.setVisible(false);

            } else if (planeta == lblSaturno) {

                lblLugarSaturno.setIcon(lblSaturno.getIcon());
                lblSaturno.setVisible(false);

            } else if (planeta == lblUrano) {

                lblLugarUrano.setIcon(lblUrano.getIcon());
                lblUrano.setVisible(false);

            } else if (planeta == lblNeptuno) {

                lblLugarNeptuno.setIcon(lblNeptuno.getIcon());
                lblNeptuno.setVisible(false);

            }

            getContentPane().revalidate();
            getContentPane().repaint();

            sumarPuntos(10);

            SwingUtilities.invokeLater(() -> {
                mostrarVentanaBonita(
                        "Lo hiciste muy bien",
                        "Uniste el planeta correctamente.",
                        "Puntaje actual: "  + GameData.puntos
                );
            });
            boolean quedan = false;

            for (Boolean b : colocados) {
                if (!b) {
                    quedan = true;
                    break;
                }
            }

            if (quedan) {

            }

        } else {

            restarPuntos(3);

            mostrarVentanaBonita(
                    "Vuelve a intentarlo",
                    "La union no es correcta.<br>Se descontaron 3 puntos.",
                    "Puntaje actual: "  + GameData.puntos
            );
            regresarPlaneta(planeta);

            int indice = planetas.indexOf(planeta);
            colocados.set(indice, false);
        }

    }

    private void regresarPlaneta(JLabel planeta) {

        if (planeta == lblMercurio) {

            planeta.setLocation(1120, -40);

        } else if (planeta == lblVenus) {

            planeta.setLocation(1120, -120);

        } else if (planeta == lblTierra) {

            planeta.setLocation(1120, -200);

        } else if (planeta == lblMarte) {

            planeta.setLocation(1120, -280);

        } else if (planeta == lblJupiter) {

            planeta.setLocation(1120, -360);

        } else if (planeta == lblSaturno) {

            planeta.setLocation(1120, -440);

        } else if (planeta == lblUrano) {

            planeta.setLocation(1120, -500);

        } else if (planeta == lblNeptuno) {

            planeta.setLocation(1120, -600);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPista;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblJupiter;
    private javax.swing.JLabel lblLugarJupiter;
    private javax.swing.JLabel lblLugarMarte;
    private javax.swing.JLabel lblLugarMercurio;
    private javax.swing.JLabel lblLugarNeptuno;
    private javax.swing.JLabel lblLugarSaturno;
    private javax.swing.JLabel lblLugarTierra;
    private javax.swing.JLabel lblLugarUrano;
    private javax.swing.JLabel lblLugarVenus;
    private javax.swing.JLabel lblMarte;
    private javax.swing.JLabel lblMercurio;
    private javax.swing.JLabel lblNeptuno;
    private javax.swing.JLabel lblSaturno;
    private javax.swing.JLabel lblTierra;
    private javax.swing.JLabel lblUrano;
    private javax.swing.JLabel lblVenus;
    // End of variables declaration//GEN-END:variables
}
