/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;

/**
 *
 * @author sayuri
 */
public class Nivel4Explocion extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nivel4Explocion.class.getName());

    private int puntos = 10;
    private int basuraEliminada = 0;
    private int basuraTotal = 0;

    private JLabel lblPuntaje;
    private JLabel lblMensaje;
    private PanelOrbitas panelOrbitas;

    private final List<JLabel> objetosBasura = new ArrayList<JLabel>();

    /**
     * Creates new form Nivel4Explocion
     */
    public Nivel4Explocion() {
        this(10);
    }

    public Nivel4Explocion(int puntosRecibidos) {
        puntos = Math.max(0, puntosRecibidos);
        initComponents();
        lblsateliteRoto.setVisible(false);

        prepararNivel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEstrella = new javax.swing.JLabel();
        btnPista = new javax.swing.JButton();
        lblsateliteRoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnsiguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEstrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estrella-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblEstrella, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 80, 70));

        btnPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Pista-removebg-preview (1).png"))); // NOI18N
        btnPista.setBorderPainted(false);
        btnPista.setContentAreaFilled(false);
        btnPista.addActionListener(this::btnPistaActionPerformed);
        getContentPane().add(btnPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 550, 150, 50));

        lblsateliteRoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/satelite-removebg-preview (1).png"))); // NOI18N
        getContentPane().add(lblsateliteRoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 90, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Nivel 4 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnsiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Siguiente-removebg-preview (1).png"))); // NOI18N
        btnsiguiente.setText("jButton2");
        btnsiguiente.setBorderPainted(false);
        btnsiguiente.setContentAreaFilled(false);
        btnsiguiente.addActionListener(this::btnsiguienteActionPerformed);
        getContentPane().add(btnsiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 600, 160, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:
        usarPista();


    }//GEN-LAST:event_btnPistaActionPerformed

    private void btnsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiguienteActionPerformed
        // TODO add your handling code here:
        irSiguienteNivel();

    }//GEN-LAST:event_btnsiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel4Explocion().setVisible(true);
            }
        });
    }

    private void prepararNivel() {
        setTitle("Nivel 4 - Limpia las orbitas");
        setResizable(false);

        configurarBotones();
        crearPanelOrbitas();
        crearMarcadores();
        crearObjetosDelNivel();
        enviarFondoAtras();
        actualizarMarcadores();
        lblEstrella.setCursor(new Cursor(Cursor.HAND_CURSOR));

        lblEstrella.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                tocarEstrella(lblEstrella);
            }
        });

    }

    private void configurarBotones() {
        btnPista.setFont(new Font("Arial", Font.BOLD, 16));
        btnPista.setForeground(Color.WHITE);
        btnPista.setBackground(new Color(70, 150, 35));
        btnPista.setBorder(BorderFactory.createLineBorder(new Color(210, 255, 90), 2));
        btnPista.setFocusPainted(false);
        btnPista.setCursor(new Cursor(Cursor.HAND_CURSOR));

        btnsiguiente.setFont(new Font("Arial", Font.BOLD, 16));
        btnsiguiente.setForeground(Color.WHITE);
        btnsiguiente.setBackground(new Color(25, 120, 220));
        btnsiguiente.setBorder(BorderFactory.createLineBorder(new Color(100, 230, 255), 2));
        btnsiguiente.setFocusPainted(false);
        btnsiguiente.setCursor(new Cursor(Cursor.HAND_CURSOR));
        /*btnsiguiente.setEnabled(false);*/
        btnsiguiente.setEnabled(true);
    }

    private void agregarComponente(java.awt.Component componente, int x, int y, int ancho, int alto) {
        getContentPane().add(componente, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, ancho, alto));
    }

    private void crearPanelOrbitas() {
        panelOrbitas = new PanelOrbitas();
        panelOrbitas.setOpaque(false);
        agregarComponente(panelOrbitas, 0, 0, 1362, 760);
        getContentPane().setComponentZOrder(panelOrbitas, 0);
    }

    private void crearMarcadores() {
        lblPuntaje = new JLabel("", SwingConstants.CENTER);
        lblPuntaje.setOpaque(true);
        lblPuntaje.setFont(new Font("Arial", Font.BOLD, 23));
        lblPuntaje.setForeground(Color.WHITE);
        lblPuntaje.setBackground(new Color(8, 34, 105));
        lblPuntaje.setBorder(BorderFactory.createLineBorder(new Color(70, 220, 255), 3));
        agregarComponente(lblPuntaje, 1170, 20, 190, 48);

        lblMensaje = new JLabel("Haz clic solo en la basura espacial.", SwingConstants.CENTER);
        lblMensaje.setOpaque(true);
        lblMensaje.setFont(new Font("Arial", Font.BOLD, 21));
        lblMensaje.setForeground(new Color(255, 240, 100));
        lblMensaje.setBackground(new Color(8, 18, 62));
        lblMensaje.setBorder(BorderFactory.createLineBorder(new Color(255, 240, 100), 2));
        agregarComponente(lblMensaje, 330, 150, 700, 42);
    }

    private void crearObjetosDelNivel() {
        basuraTotal = 0;
        basuraEliminada = 0;
        objetosBasura.clear();

        crearBasura(150, 410);
        crearBasura(220, 240);
        crearBasura(600, 245);
        crearBasura(790, 350);
        crearBasura(1010, 260);
        crearBasura(430, 470);
        crearBasura(690, 535);
        crearBasura(1080, 500);

        // Estrellas
        crearEstrella(835, 210);
        crearEstrella(1120, 420);
        crearEstrella(540, 520);

    }

    private void registrarBasura(JLabel basura) {
        objetosBasura.add(basura);
        basuraTotal++;
    }

    private void crearBasura(int x, int y) {
        final JLabel basura = new JLabel();
        basura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/satelite-removebg-preview (1).png")));
        basura.setCursor(new Cursor(Cursor.HAND_CURSOR));
        basura.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                eliminarBasura(basura);
            }
        });

        registrarBasura(basura);
        agregarComponente(basura, x, y, 70, 60);
        getContentPane().setComponentZOrder(basura, 0);
    }

    private void crearEstrella(int x, int y) {
        final JLabel estrella = new JLabel();
        estrella.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estrella-removebg-preview (1).png")));
        estrella.setCursor(new Cursor(Cursor.HAND_CURSOR));
        estrella.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt) {
                tocarEstrella(estrella);
            }
        });

        agregarComponente(estrella, x, y, 80, 70);
        getContentPane().setComponentZOrder(estrella, 0);
    }

    private void eliminarBasura(JLabel basura) {
        if (!basura.isVisible()) {
            return;
        }

        basura.setVisible(false);
        basuraEliminada++;

        if (basuraEliminada % 4 == 0) {
            puntos += 10;
            lblMensaje.setText("Muy bien: limpiaste 4 basuras. +10 puntos.");
            mostrarVentanaBonita("Buen trabajo", "Eliminaste 4 objetos de basura espacial.\nGanaste 10 puntos.\nPuntaje actual: " + puntos);
        } else {
            lblMensaje.setText("Basura eliminada. Sigue limpiando las orbitas.");
        }

        actualizarMarcadores();

        if (basuraEliminada == basuraTotal) {
            completarNivel();
        }
    }

    private void tocarEstrella(JLabel estrella) {
        puntos = Math.max(0, puntos - 3);
        actualizarMarcadores();

        lblMensaje.setText("Cuidado: las estrellas no son basura. -3 puntos.");
        mostrarVentanaBonita("Cuidado", "Hiciste clic en una estrella.\nLas estrellas no se eliminan.\nSe descontaron 3 puntos.");
    }

    private void usarPista() {
        puntos = Math.max(0, puntos - 3);
        actualizarMarcadores();

        int faltan = basuraTotal - basuraEliminada;
        lblMensaje.setText("Pista usada: -3 puntos.");
        mostrarVentanaBonita("Pista", "Busca los satelites rotos o piezas grises.\nNo hagas clic en las estrellas amarillas.\nBasura restante: " + faltan);
    }

    private void completarNivel() {
        panelOrbitas.setOrbitasBrillantes(true);
        btnsiguiente.setEnabled(true);
        btnPista.setEnabled(false);

        lblMensaje.setText("Excelente: las orbitas vuelven a brillar.");
        mostrarVentanaBonita("Nivel completado", "Limpiaste toda la basura espacial.\nLas orbitas vuelven a brillar.\nPuntaje actual: " + puntos);
    }

    private void actualizarMarcadores() {
        lblPuntaje.setText("Puntos: " + puntos);
    }

    private void irSiguienteNivel() {
        if (basuraEliminada < basuraTotal) {
            mostrarVentanaBonita("Aun falta", "Primero elimina toda la basura espacial.");
            return;
        }

        mostrarVentanaBonita("Muy bien", "Puntaje actual: " + puntos + "\nYa puedes continuar.");

        // Cambia Nivel5 por el nombre real de tu siguiente formulario.
        // Nivel5 nivel = new Nivel5(puntos);
        // nivel.setVisible(true);
        // this.dispose();
    }

    private void enviarFondoAtras() {
        getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    private void mostrarVentanaBonita(String titulo, String mensaje) {
        final boolean esAlerta = titulo.toLowerCase().contains("cuidado") || titulo.toLowerCase().contains("falta");
        final Color colorAcento = esAlerta ? new Color(255, 95, 80) : new Color(70, 220, 255);
        final Color colorBrillo = esAlerta ? new Color(255, 230, 85) : new Color(255, 235, 95);

        final JDialog dialogo = new JDialog(this, titulo, true);
        dialogo.setSize(540, 315);
        dialogo.setLocationRelativeTo(this);
        dialogo.setUndecorated(true);

        JPanel panel = new JPanel() {
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                GradientPaint fondo = new GradientPaint(0, 0, new Color(8, 18, 62), getWidth(), getHeight(), new Color(48, 10, 90));
                g2.setPaint(fondo);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 28, 28);

                g2.setColor(colorAcento);
                g2.setStroke(new BasicStroke(4));
                g2.drawRoundRect(3, 3, getWidth() - 7, getHeight() - 7, 28, 28);
            }
        };

        panel.setLayout(null);

        JLabel lblIcono = new JLabel(esAlerta ? "!" : "*", SwingConstants.CENTER);
        lblIcono.setFont(new Font("Arial", Font.BOLD, 48));
        lblIcono.setForeground(colorBrillo);
        lblIcono.setBounds(35, 20, 70, 60);
        panel.add(lblIcono);

        JLabel lblTitulo = new JLabel(titulo, SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 28));
        lblTitulo.setForeground(colorBrillo);
        lblTitulo.setBounds(105, 28, 385, 42);
        panel.add(lblTitulo);

        JTextArea txtMensaje = new JTextArea(mensaje);
        txtMensaje.setFont(new Font("Arial", Font.BOLD, 19));
        txtMensaje.setForeground(Color.WHITE);
        txtMensaje.setBackground(new Color(10, 26, 78));
        txtMensaje.setOpaque(true);
        txtMensaje.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(colorAcento, 2),
                BorderFactory.createEmptyBorder(14, 18, 14, 18)));
        txtMensaje.setEditable(false);
        txtMensaje.setFocusable(false);
        txtMensaje.setLineWrap(true);
        txtMensaje.setWrapStyleWord(true);
        txtMensaje.setBounds(50, 100, 440, 96);
        panel.add(txtMensaje);

        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setFont(new Font("Arial", Font.BOLD, 17));
        btnAceptar.setForeground(Color.WHITE);
        btnAceptar.setBackground(esAlerta ? new Color(210, 65, 70) : new Color(25, 120, 220));
        btnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.setBorder(BorderFactory.createLineBorder(colorBrillo, 2));
        btnAceptar.setBounds(190, 230, 160, 44);
        btnAceptar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                dialogo.dispose();
            }
        });

        panel.add(btnAceptar);

        dialogo.setContentPane(panel);
        dialogo.setVisible(true);
    }

    private class PanelOrbitas extends JPanel {

        private boolean orbitasBrillantes = false;

        public void setOrbitasBrillantes(boolean orbitasBrillantes) {
            this.orbitasBrillantes = orbitasBrillantes;
            repaint();
        }

        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

            if (!orbitasBrillantes) {
                return;
            }

            g2.setStroke(new BasicStroke(5));
            g2.setColor(new Color(120, 245, 255, 220));

            int centroX = 681;
            int centroY = 380;

            for (int i = 0; i < 6; i++) {
                int ancho = 300 + i * 145;
                int alto = 90 + i * 52;
                g2.drawOval(centroX - ancho / 2, centroY - alto / 2, ancho, alto);
            }

            g2.setColor(new Color(255, 245, 100));
            g2.setFont(new Font("Arial", Font.BOLD, 28));
            g2.drawString("Orbitas limpias y brillantes", 485, 680);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPista;
    private javax.swing.JButton btnsiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblEstrella;
    private javax.swing.JLabel lblsateliteRoto;
    // End of variables declaration//GEN-END:variables
}
