/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.GradientPaint;
import java.awt.Point;
import java.awt.RenderingHints;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextArea;
import javax.swing.SwingConstants;
import javax.swing.Timer;

/**
 *
 * @author sayuri
 */
public class Nivel3Ordenar extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Nivel3Ordenar.class.getName());

   private int puntos = 10;
    private int aciertos = 0;

    private JLabel lblPuntaje;
    private JLabel lblMensaje;

    private PanelLineas panelLineas;
    private JLabel planetaSeleccionado = null;

    private final Map<JLabel, String> planetas = new HashMap<JLabel, String>();
    private final Map<JTextArea, String> caracteristicas = new HashMap<JTextArea, String>();
    private final Map<String, String> respuestasCorrectas = new HashMap<String, String>();
    private final Set<JLabel> planetasUnidos = new HashSet<JLabel>();
    private final Set<JTextArea> caracteristicasUnidas = new HashSet<JTextArea>();
    private final List<LineaUnion> lineas = new ArrayList<LineaUnion>();
    /**
     * Creates new form Nivel3Ordenar
     */
    public Nivel3Ordenar() {
        this(10);
    }

    public Nivel3Ordenar(int puntosRecibidos) {
        puntos = Math.max(0, puntosRecibidos);
        initComponents();
        prepararNivelOrdenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtnSiguiente = new javax.swing.JButton();
        btnPista = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/booton_siguiente_3-removebg-preview (1).png"))); // NOI18N
        BtnSiguiente.setBorderPainted(false);
        BtnSiguiente.setContentAreaFilled(false);
        BtnSiguiente.setFocusPainted(false);
        BtnSiguiente.addActionListener(this::BtnSiguienteActionPerformed);
        getContentPane().add(BtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 610, 160, 50));

        btnPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/booton_pista_3-removebg-preview (1).png"))); // NOI18N
        btnPista.setBorderPainted(false);
        btnPista.setContentAreaFilled(false);
        btnPista.setFocusPainted(false);
        btnPista.addActionListener(this::btnPistaActionPerformed);
        getContentPane().add(btnPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 610, 160, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nivel (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1362, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:

        usarPista();
    }//GEN-LAST:event_btnPistaActionPerformed

    private void BtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSiguienteActionPerformed
        // TODO add your handling code here:

        irSiguienteNivel();
    }//GEN-LAST:event_BtnSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
      try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nivel3Ordenar().setVisible(true);
            }
        });
    }

   private void prepararNivelOrdenar() {
        BtnSiguiente.setText("Siguiente");
        btnPista.setText("Pista (-3)");

        BtnSiguiente.setFocusable(false);
        btnPista.setFocusable(false);

        crearPanelDeLineas();
        crearMarcadores();
        crearPlanetasYCaracteristicas();
        crearRespuestasCorrectas();
        enviarFondoAtras();
        actualizarMarcadores();
    }

    private void agregarComponente(Component componente, int x, int y, int ancho, int alto) {
        getContentPane().add(componente, new org.netbeans.lib.awtextra.AbsoluteConstraints(x, y, ancho, alto));
    }

    private void crearPanelDeLineas() {
        panelLineas = new PanelLineas();
        panelLineas.setOpaque(false);
        agregarComponente(panelLineas, 0, 0, 1362, 760);
        getContentPane().setComponentZOrder(panelLineas, 0);
    }

    private void crearMarcadores() {
        lblPuntaje = new JLabel("", SwingConstants.CENTER);
        lblPuntaje.setOpaque(true);
        lblPuntaje.setFont(new Font("Arial", Font.BOLD, 23));
        lblPuntaje.setForeground(Color.WHITE);
        lblPuntaje.setBackground(new Color(8, 34, 105));
        lblPuntaje.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(70, 220, 255), 3),
                BorderFactory.createEmptyBorder(4, 8, 4, 8)));
        agregarComponente(lblPuntaje, 1060, 35, 190, 48);

        lblMensaje = new JLabel("Une cada planeta con su caracteristica.", SwingConstants.CENTER);
        lblMensaje.setFont(new Font("Arial", Font.BOLD, 21));
        lblMensaje.setForeground(new Color(255, 240, 100));
        lblMensaje.setOpaque(true);
        lblMensaje.setBackground(new Color(8, 18, 62));
        lblMensaje.setBorder(BorderFactory.createLineBorder(new Color(255, 240, 100), 2));
        agregarComponente(lblMensaje, 360, 92, 650, 35);
    }

    private void crearPlanetasYCaracteristicas() {
        crearPlaneta("Mercurio", "/imagen/MercurioA1 (1).png", 80, 125, 290, 70);
        crearPlaneta("Tierra", "/imagen/TierraA1 (1).png", 80, 225, 290, 70);
        crearPlaneta("Marte", "/imagen/marteA1 (2) (1).png", 80, 325, 290, 70);
        crearPlaneta("Jupiter", "/imagen/jupiterA1 (1).png", 80, 425, 290, 70);
        crearPlaneta("Saturno", "/imagen/saturnoA (1).png", 80, 525, 290, 70);

        crearCaracteristica("planeta_rojo", "Es conocido como\nel planeta rojo.", 930, 130, new Color(255, 215, 215), new Color(230, 90, 90));
        crearCaracteristica("anillos", "Tiene grandes\nanillos alrededor.", 930, 230, new Color(230, 218, 255), new Color(130, 80, 220));
        crearCaracteristica("cercano_sol", "Es el planeta\nmas cercano al Sol.", 930, 330, new Color(255, 235, 180), new Color(245, 170, 20));
        crearCaracteristica("mas_grande", "Es el planeta\nmas grande.", 930, 430, new Color(215, 240, 255), new Color(60, 170, 230));
        crearCaracteristica("vida", "Es el unico planeta\ndonde hay vida.", 930, 530, new Color(230, 245, 210), new Color(115, 180, 65));
    }

    private void crearPlaneta(String nombre, String rutaImagen, int x, int y, int ancho, int alto) {
        final JLabel label = new JLabel(nombre, SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.BOLD, 28));
        label.setForeground(Color.WHITE);
        label.setIcon(new javax.swing.ImageIcon(getClass().getResource(rutaImagen)));
        label.setHorizontalTextPosition(SwingConstants.RIGHT);
        label.setIconTextGap(22);
        label.setOpaque(true);
        label.setBackground(new Color(8, 35, 90));
        label.setBorder(BorderFactory.createLineBorder(new Color(35, 95, 190), 3));
        label.setCursor(new Cursor(Cursor.HAND_CURSOR));

        agregarComponente(label, x, y, ancho, alto);
        planetas.put(label, nombre);

        label.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarPlaneta(label);
            }
        });
    }

    private void crearCaracteristica(String clave, String texto, int x, int y, Color fondo, Color borde) {
        final JTextArea area = new JTextArea(texto);
        area.setFont(new Font("Arial", Font.BOLD, 22));
        area.setForeground(new Color(10, 20, 55));
        area.setBackground(fondo);
        area.setBorder(BorderFactory.createLineBorder(borde, 4));
        area.setEditable(false);
        area.setFocusable(false);
        area.setLineWrap(true);
        area.setWrapStyleWord(true);
        area.setCursor(new Cursor(Cursor.HAND_CURSOR));
        area.setMargin(new java.awt.Insets(12, 25, 10, 20));

        agregarComponente(area, x, y, 380, 82);
        caracteristicas.put(area, clave);

        area.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionarCaracteristica(area);
            }
        });
    }

    private void crearRespuestasCorrectas() {
        respuestasCorrectas.put("Mercurio", "cercano_sol");
        respuestasCorrectas.put("Tierra", "vida");
        respuestasCorrectas.put("Marte", "planeta_rojo");
        respuestasCorrectas.put("Jupiter", "mas_grande");
        respuestasCorrectas.put("Saturno", "anillos");
    }

    private void seleccionarPlaneta(JLabel planeta) {
        if (planetasUnidos.contains(planeta)) {
            lblMensaje.setText("Ese planeta ya esta unido.");
            return;
        }

        if (planetaSeleccionado != null && !planetasUnidos.contains(planetaSeleccionado)) {
            planetaSeleccionado.setBorder(BorderFactory.createLineBorder(new Color(35, 95, 190), 3));
        }

        planetaSeleccionado = planeta;
        planeta.setBorder(BorderFactory.createLineBorder(Color.YELLOW, 4));
        lblMensaje.setText("Ahora elige su caracteristica.");
    }

    private void seleccionarCaracteristica(JTextArea caracteristica) {
        if (planetaSeleccionado == null) {
            lblMensaje.setText("Primero selecciona un planeta.");
            return;
        }

        if (caracteristicasUnidas.contains(caracteristica)) {
            lblMensaje.setText("Esa caracteristica ya fue usada.");
            return;
        }

        String nombrePlaneta = planetas.get(planetaSeleccionado);
        String claveCaracteristica = caracteristicas.get(caracteristica);
        String respuestaCorrecta = respuestasCorrectas.get(nombrePlaneta);

        if (respuestaCorrecta.equals(claveCaracteristica)) {
            unirCorrectamente(planetaSeleccionado, caracteristica);
        } else {
            respuestaIncorrecta();
        }
    }

    private void unirCorrectamente(JLabel planeta, JTextArea caracteristica) {
        puntos += 10;
        aciertos++;

        planetasUnidos.add(planeta);
        caracteristicasUnidas.add(caracteristica);

        planeta.setBorder(BorderFactory.createLineBorder(new Color(80, 255, 120), 4));
        caracteristica.setBorder(BorderFactory.createLineBorder(new Color(80, 255, 120), 4));

        lineas.add(new LineaUnion(centroDerecha(planeta), centroIzquierda(caracteristica), new Color(70, 240, 255)));
        panelLineas.repaint();

        planetaSeleccionado = null;
        actualizarMarcadores();
        lblMensaje.setText("Muy bien: +10 puntos.");
        mostrarEstrellitas(centroIzquierda(caracteristica));

        if (aciertos == 5) {
            mostrarVentanaBonita("Lo hiciste muy bien", "Uniste todos los planetas con sus caracteristicas.\nPuntaje actual: " + puntos);
        }
    }

    private void respuestaIncorrecta() {
        restarPuntos(3);
        actualizarMarcadores();

        if (planetaSeleccionado != null) {
            planetaSeleccionado.setBorder(BorderFactory.createLineBorder(new Color(35, 95, 190), 3));
        }

        planetaSeleccionado = null;

        lblMensaje.setText("Incorrecto: -3 puntos. Vuelve a intentarlo.");
        mostrarVentanaBonita("Vuelve a intentarlo", "La union no es correcta.\nSe descontaron 3 puntos.\nPuntaje actual: " + puntos);
    }

    private void usarPista() {
        restarPuntos(3);
        actualizarMarcadores();

        String pista;

        if (aciertos < 2) {
            pista = "Lee primero el nombre del planeta.\\nLuego busca la descripción que más se parezca.";
        } else {
            pista = "Pregúntate:\\n¿Qué hace especial a este planeta?";
        }

        lblMensaje.setText("Pista usada: -3 puntos.");
        mostrarVentanaBonita("Pista (-3 puntos)", pista + "\nPuntaje actual: " + puntos);
    }

    private void restarPuntos(int cantidad) {
        puntos = Math.max(0, puntos - cantidad);
    }

    private void actualizarMarcadores() {
        lblPuntaje.setText("Puntos: " + puntos);
    }

    private Point centroDerecha(JLabel label) {
        return new Point(label.getX() + label.getWidth(), label.getY() + label.getHeight() / 2);
    }

    private Point centroIzquierda(JTextArea area) {
        return new Point(area.getX(), area.getY() + area.getHeight() / 2);
    }

    private void irSiguienteNivel() {
    if (aciertos < 5) {
        mostrarVentanaBonita("Aun falta", "Primero une los 5 planetas con sus caracteristicas.");
        return;
    }

    mostrarVentanaBonita("Nivel completado",
            "Puntaje actual: " + puntos + "\nYa puedes continuar.");

    Nivel4Explocion nivel4 = new Nivel4Explocion();
    nivel4.setVisible(true);
    this.dispose();
}

    private void enviarFondoAtras() {
        getContentPane().setComponentZOrder(jLabel1, getContentPane().getComponentCount() - 1);
        getContentPane().revalidate();
        getContentPane().repaint();
    }

    private void mostrarEstrellitas(Point centro) {
        for (int i = 0; i < 8; i++) {
            final JLabel estrella = new JLabel("*", SwingConstants.CENTER);
            estrella.setFont(new Font("Arial", Font.BOLD, 25));
            estrella.setForeground(new Color(255, 240, 80));

            int x = centro.x - 25 + (int) (Math.random() * 50);
            int y = centro.y - 25 + (int) (Math.random() * 50);

            agregarComponente(estrella, x, y, 35, 35);
            getContentPane().setComponentZOrder(estrella, 0);
            enviarFondoAtras();

            Timer borrar = new Timer(550, new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent e) {
                    getContentPane().remove(estrella);
                    getContentPane().repaint();
                }
            });
            borrar.setRepeats(false);
            borrar.start();
        }
    }

    private void mostrarVentanaBonita(String titulo, String mensaje) {
        final boolean esAlerta = titulo.toLowerCase().contains("vuelve") || titulo.toLowerCase().contains("falta");
        final Color colorAcento = esAlerta ? new Color(255, 95, 80) : new Color(70, 220, 255);
        final Color colorBrillo = esAlerta ? new Color(255, 230, 85) : new Color(255, 235, 95);

        final JDialog dialogo = new JDialog(this, titulo, true);
        dialogo.setSize(540, 315);
        dialogo.setLocationRelativeTo(this);
        dialogo.setUndecorated(true);

        JPanel panel = new JPanel() {
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);

                Graphics2D g2 = (Graphics2D) g;
                g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                GradientPaint fondo = new GradientPaint(
                        0, 0, new Color(8, 18, 62),
                        getWidth(), getHeight(), new Color(48, 10, 90)
                );

                g2.setPaint(fondo);
                g2.fillRoundRect(0, 0, getWidth(), getHeight(), 28, 28);

                g2.setColor(colorAcento);
                g2.setStroke(new BasicStroke(4));
                g2.drawRoundRect(3, 3, getWidth() - 7, getHeight() - 7, 28, 28);

                g2.setColor(new Color(colorAcento.getRed(), colorAcento.getGreen(), colorAcento.getBlue(), 80));
                g2.fillRoundRect(28, 22, getWidth() - 56, 54, 20, 20);
            }
        };

        panel.setLayout(null);

        JLabel lblIcono = new JLabel(esAlerta ? "!" : "*", SwingConstants.CENTER);
        lblIcono.setFont(new Font("Arial", Font.BOLD, 48));
        lblIcono.setForeground(colorBrillo);
        lblIcono.setBounds(35, 20, 70, 60);
        panel.add(lblIcono);

        JLabel lblTitulo = new JLabel(titulo, SwingConstants.CENTER);
        lblTitulo.setFont(new Font("Arial", Font.BOLD, 28));
        lblTitulo.setForeground(colorBrillo);
        lblTitulo.setBounds(105, 28, 385, 42);
        panel.add(lblTitulo);

        JTextArea txtMensaje = new JTextArea(mensaje);
        txtMensaje.setFont(new Font("Arial", Font.BOLD, 19));
        txtMensaje.setForeground(Color.WHITE);
        txtMensaje.setBackground(new Color(10, 26, 78));
        txtMensaje.setOpaque(true);
        txtMensaje.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(colorAcento, 2),
                BorderFactory.createEmptyBorder(14, 18, 14, 18)));
        txtMensaje.setEditable(false);
        txtMensaje.setFocusable(false);
        txtMensaje.setLineWrap(true);
        txtMensaje.setWrapStyleWord(true);
        txtMensaje.setBounds(50, 100, 440, 96);
        panel.add(txtMensaje);

        JButton btnAceptar = new JButton("Aceptar");
        btnAceptar.setFont(new Font("Arial", Font.BOLD, 17));
        btnAceptar.setForeground(Color.WHITE);
        btnAceptar.setBackground(esAlerta ? new Color(210, 65, 70) : new Color(25, 120, 220));
        btnAceptar.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btnAceptar.setFocusPainted(false);
        btnAceptar.setBorder(BorderFactory.createLineBorder(colorBrillo, 2));
        btnAceptar.setBounds(190, 230, 160, 44);
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent e) {
                dialogo.dispose();
            }
        });
        panel.add(btnAceptar);

        dialogo.setContentPane(panel);
        dialogo.setVisible(true);
    }

    private class PanelLineas extends JPanel {

        protected void paintComponent(Graphics g) {
            super.paintComponent(g);

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setStroke(new BasicStroke(5, BasicStroke.CAP_ROUND, BasicStroke.JOIN_ROUND));

            for (LineaUnion linea : lineas) {
                g2.setColor(linea.color);
                g2.drawLine(linea.inicio.x, linea.inicio.y, linea.fin.x, linea.fin.y);

                g2.setColor(Color.WHITE);
                g2.fillOval(linea.inicio.x - 5, linea.inicio.y - 5, 10, 10);
                g2.fillOval(linea.fin.x - 5, linea.fin.y - 5, 10, 10);
            }
        }
    }

    private static class LineaUnion {

        Point inicio;
        Point fin;
        Color color;

        LineaUnion(Point inicio, Point fin, Color color) {
            this.inicio = inicio;
            this.fin = fin;
            this.color = color;
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSiguiente;
    private javax.swing.JButton btnPista;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
