/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class QuizViaLactea1 extends javax.swing.JFrame {
    
   private int puntos = 10; // puntos iniciales, ajusta el numero que quieras
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizViaLactea1.class.getName());


 
    public QuizViaLactea1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jBtnViaLactea = new javax.swing.JButton();
        jBtnSaturno = new javax.swing.JButton();
        jBtnLuna = new javax.swing.JButton();
        jBtnSol = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jBtnPuntos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 190, 60));

        jBtnViaLactea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Opcion D (1).png"))); // NOI18N
        jBtnViaLactea.setBorderPainted(false);
        jBtnViaLactea.setContentAreaFilled(false);
        jBtnViaLactea.addActionListener(this::jBtnViaLacteaActionPerformed);
        getContentPane().add(jBtnViaLactea, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 170, 170));

        jBtnSaturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpcionC (1).png"))); // NOI18N
        jBtnSaturno.setBorderPainted(false);
        jBtnSaturno.setContentAreaFilled(false);
        jBtnSaturno.addActionListener(this::jBtnSaturnoActionPerformed);
        getContentPane().add(jBtnSaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 180, 170));

        jBtnLuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpciosB (1).png"))); // NOI18N
        jBtnLuna.setBorderPainted(false);
        jBtnLuna.setContentAreaFilled(false);
        jBtnLuna.addActionListener(this::jBtnLunaActionPerformed);
        getContentPane().add(jBtnLuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 190, 180));

        jBtnSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpcionA (2).png"))); // NOI18N
        jBtnSol.setBorderPainted(false);
        jBtnSol.setContentAreaFilled(false);
        jBtnSol.addActionListener(this::jBtnSolActionPerformed);
        getContentPane().add(jBtnSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 180, 170));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Ayuda (1) (1).png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, 150));

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        jLabel3.setText("¿Dónde vivimos dentro del universo?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 560, 70));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnAdelante.png"))); // NOI18N
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 120, 90));

        jBtnPuntos.setBackground(new java.awt.Color(51, 0, 51));
        jBtnPuntos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jBtnPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPuntos.setText("10");
        jBtnPuntos.addActionListener(this::jBtnPuntosActionPerformed);
        getContentPane().add(jBtnPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(1015, 143, 50, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Acumulador (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 280, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Lactea2 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1170, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBtnPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPuntosActionPerformed

    private void jBtnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolActionPerformed
       
        manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnSolActionPerformed

    private void jBtnSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaturnoActionPerformed
    manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnSaturnoActionPerformed

    private void jBtnLunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLunaActionPerformed
        manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnLunaActionPerformed

    private void jBtnViaLacteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViaLacteaActionPerformed
         puntos += 3; // o los puntos que quieras dar por acertar
    actualizarPuntosEnPantalla();
    JOptionPane.showMessageDialog(this, "¡Correcto! Vivimos en la Vía Láctea.", "¡Bien hecho!", JOptionPane.INFORMATION_MESSAGE);
    // Aqui despues puedes abrir la siguiente mision
    }//GEN-LAST:event_jBtnViaLacteaActionPerformed

    
    private void manejarRespuestaIncorrecta() {
    int opcion = JOptionPane.showConfirmDialog(
        this,
        "¡Oops! Incorrecto.\n¿Necesitas una pista?\n(cuesta 2 puntos, sin pista pierdes 3)",
        "Respuesta incorrecta",
        JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE
    );

    if (opcion == JOptionPane.YES_OPTION) {
        // Quiso pista: resta 2 puntos y muestra la pista
        puntos -= 2;
        JOptionPane.showMessageDialog(
            this,
            "Pista: \"Nuestra casa no tiene anillos, y no es el Sol ni la Luna...\"",
            "Aquí está tu pista",
            JOptionPane.INFORMATION_MESSAGE
        );
    } else {
        // No quiso pista: resta 3 puntos
        puntos -= 3;
        JOptionPane.showMessageDialog(
            this,
            "Sin pista. Inténtalo de nuevo.",
            "Sigue intentando",
            JOptionPane.INFORMATION_MESSAGE
        );
    }

    actualizarPuntosEnPantalla();
}

private void actualizarPuntosEnPantalla() {
    jBtnPuntos.setText("PUNTOS ACUMULADOS: " + puntos);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuizViaLactea1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnLuna;
    private javax.swing.JButton jBtnPuntos;
    private javax.swing.JButton jBtnSaturno;
    private javax.swing.JButton jBtnSol;
    private javax.swing.JButton jBtnViaLactea;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
