/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import java.awt.Image;
import java.net.URL;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JButton;
/**
 *
 * @author Usuario
 */
public class QuizViaLactea1 extends javax.swing.JFrame {
      public int puntos = 10; // puntos iniciales, ajusta el numero que quieras
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizViaLactea1.class.getName());
    private Clip clipFondo; // audio que suena al abrir esta pantalla
 private Clip clipMusica; 
 
    public QuizViaLactea1() {
        initComponents();

        // --- Reproduce el audio al abrir el formulario ---
         try {
        java.net.URL urlSonido = getClass().getResource("/audio/Quiz1.wav"); // <-- cambia el nombre si tu archivo es otro
        System.out.println("URL encontrada: " + urlSonido);
        clipMusica = AudioSystem.getClip();
        AudioInputStream audioIn = AudioSystem.getAudioInputStream(urlSonido);
        clipMusica.open(audioIn);
        clipMusica.start(); // se reproduce una sola vez, no en bucle
    } catch (Exception ex) {
        logger.log(java.util.logging.Level.SEVERE, "No se pudo reproducir la música", ex);
    }
       
        

        // --- Animacion de "respiracion" (zoom) para los botones de respuesta y el boton de Ayuda ---
        JButton[] botonesAnimados = { jBtnSol, jBtnLuna, jBtnSaturno, jBtnViaLactea, jBtnAyuda };
 
        final ImageIcon[] iconosOriginales = new ImageIcon[botonesAnimados.length];
        final int[] anchoBase = new int[botonesAnimados.length];
        final int[] altoBase = new int[botonesAnimados.length];
        final int[] centroX = new int[botonesAnimados.length];
        final int[] centroY = new int[botonesAnimados.length];
 
        for (int i = 0; i < botonesAnimados.length; i++) {
            JButton b = botonesAnimados[i];
            iconosOriginales[i] = (ImageIcon) b.getIcon();
            anchoBase[i] = b.getWidth();
            altoBase[i]  = b.getHeight();
            centroX[i]   = b.getX() + anchoBase[i] / 2;
            centroY[i]   = b.getY() + altoBase[i] / 2;
        }
 
        final double[] anguloBotones = {0};
        final double amplitudBotones = 0.05; 
 
        javax.swing.Timer timerBotones = new javax.swing.Timer(30, e -> {
            anguloBotones[0] += 0.06;
            double factor = 1.0 + amplitudBotones * Math.sin(anguloBotones[0]);
 
            for (int i = 0; i < botonesAnimados.length; i++) {
                int w = (int) (anchoBase[i] * factor);
                int h = (int) (altoBase[i] * factor);
                Image escalado = iconosOriginales[i].getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
                botonesAnimados[i].setIcon(new ImageIcon(escalado));
                botonesAnimados[i].setBounds(centroX[i] - w / 2, centroY[i] - h / 2, w, h);
            }
        });
        timerBotones.start();
 
        // --- Animacion de zoom (pulso) para el titulo de la pregunta ---
        final java.awt.Font fuenteBaseTitulo = jLabel3.getFont();
        final float tamanoBaseTitulo = fuenteBaseTitulo.getSize2D();
        final double amplitudTitulo = 0.06; // 6% de variacion de tamaño
        final double[] anguloTitulo = {0};
 
        javax.swing.Timer timerTitulo = new javax.swing.Timer(40, e -> {
            anguloTitulo[0] += 0.05;
            double factor = 1.0 + amplitudTitulo * Math.sin(anguloTitulo[0]);
            float nuevoTamano = (float) (tamanoBaseTitulo * factor);
            jLabel3.setFont(fuenteBaseTitulo.deriveFont(nuevoTamano));
        });
        timerTitulo.start();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jBtnViaLactea = new javax.swing.JButton();
        jBtnSaturno = new javax.swing.JButton();
        jBtnLuna = new javax.swing.JButton();
        jBtnSol = new javax.swing.JButton();
        jBtnAyuda = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jBtnSiguiente = new javax.swing.JButton();
        jBtnPuntos = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 190, 60));

        jBtnViaLactea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Opcion D (1).png"))); // NOI18N
        jBtnViaLactea.setBorderPainted(false);
        jBtnViaLactea.setContentAreaFilled(false);
        jBtnViaLactea.addActionListener(this::jBtnViaLacteaActionPerformed);
        getContentPane().add(jBtnViaLactea, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 520, 170, 170));

        jBtnSaturno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpcionC (1).png"))); // NOI18N
        jBtnSaturno.setBorderPainted(false);
        jBtnSaturno.setContentAreaFilled(false);
        jBtnSaturno.addActionListener(this::jBtnSaturnoActionPerformed);
        getContentPane().add(jBtnSaturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 180, 170));

        jBtnLuna.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpciosB (1).png"))); // NOI18N
        jBtnLuna.setBorderPainted(false);
        jBtnLuna.setContentAreaFilled(false);
        jBtnLuna.addActionListener(this::jBtnLunaActionPerformed);
        getContentPane().add(jBtnLuna, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 190, 180));

        jBtnSol.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/OpcionA (2).png"))); // NOI18N
        jBtnSol.setBorderPainted(false);
        jBtnSol.setContentAreaFilled(false);
        jBtnSol.addActionListener(this::jBtnSolActionPerformed);
        getContentPane().add(jBtnSol, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 180, 170));

        jBtnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Ayuda (1) (1).png"))); // NOI18N
        jBtnAyuda.setBorderPainted(false);
        jBtnAyuda.setContentAreaFilled(false);
        jBtnAyuda.addActionListener(this::jBtnAyudaActionPerformed);
        getContentPane().add(jBtnAyuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 160, 150));

        jLabel3.setFont(new java.awt.Font("Swis721 BlkCn BT", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 153));
        jLabel3.setText("¿Dónde vivimos dentro del universo?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 560, 70));

        jBtnSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnAdelante.png"))); // NOI18N
        jBtnSiguiente.setBorderPainted(false);
        jBtnSiguiente.setContentAreaFilled(false);
        jBtnSiguiente.addActionListener(this::jBtnSiguienteActionPerformed);
        getContentPane().add(jBtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 580, 120, 90));

        jBtnPuntos.setBackground(new java.awt.Color(51, 0, 51));
        jBtnPuntos.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jBtnPuntos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPuntos.setText("10");
        jBtnPuntos.addActionListener(this::jBtnPuntosActionPerformed);
        getContentPane().add(jBtnPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(985, 133, 100, 60));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Acumulador (1).png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 60, 280, 130));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Lactea2 (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1170, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void jBtnPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPuntosActionPerformed
  
    }//GEN-LAST:event_jBtnPuntosActionPerformed

    private void jBtnSolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSolActionPerformed
       
        manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnSolActionPerformed

    private void jBtnSaturnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSaturnoActionPerformed
    manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnSaturnoActionPerformed

    private void jBtnLunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnLunaActionPerformed
        manejarRespuestaIncorrecta();
    }//GEN-LAST:event_jBtnLunaActionPerformed

    private void jBtnViaLacteaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnViaLacteaActionPerformed
       int puntosGanados = 10;
        puntos += puntosGanados; // Suma 10 puntos por responder correctamente
        actualizarPuntosEnPantalla();
        VentanaPersonalizada vp = new VentanaPersonalizada();
        vp.mostrarExitoPersonalizado(this, puntosGanados);
        
                                                 
    }//GEN-LAST:event_jBtnViaLacteaActionPerformed

    private void jBtnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAyudaActionPerformed
     puntos -= 2; // Resta 2 puntos por usar la ayuda
        actualizarPuntosEnPantalla();
 
        VentanaPersonalizada vp = new VentanaPersonalizada();
        vp.mostrarPistaPersonalizada(this,
                "Nuestra casa no tiene anillos,"
                        + " y no es el Sol ni la Luna...");
                                             
    }//GEN-LAST:event_jBtnAyudaActionPerformed

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
     // --- Corta el audio antes de pasar a la siguiente pantalla ---
      
    if (clipMusica != null && clipMusica.isRunning()) {
        clipMusica.stop();
        clipMusica.close();
    }
        QuizViaLactea2 quiz = new QuizViaLactea2();
    quiz.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jBtnSiguienteActionPerformed


   private void manejarRespuestaIncorrecta() {
    VentanaPersonalizada vp = new VentanaPersonalizada();
    // Le pasamos "this" (el juego) y tu botón "jBtnPuntos"
    vp.mostrarErrorPersonalizado(this, jBtnPuntos); 
}
 
    // CAMBIO: Se cambió a public para que VentanaPersonalizada pueda llamarlo
    private int puntosMostrados = puntos; // valor que se ve actualmente en pantalla (para animar desde aquí)
 
    public void actualizarPuntosEnPantalla() {
        final int origen = puntosMostrados;
        final int destino = puntos;
        final int diferencia = destino - origen;
        if (diferencia == 0) {
            jBtnPuntos.setText(String.valueOf(destino));
            return;
        }
        final int pasos = 15;
        final int[] paso = {0};
        javax.swing.Timer timerContador = new javax.swing.Timer(20, null);
        timerContador.addActionListener(e -> {
            paso[0]++;
            double avance = Math.min(1.0, paso[0] / (double) pasos);
            int valorActual = origen + (int) Math.round(diferencia * avance);
            jBtnPuntos.setText(String.valueOf(valorActual));
            if (paso[0] >= pasos) {
                jBtnPuntos.setText(String.valueOf(destino));
                puntosMostrados = destino;
                ((javax.swing.Timer) e.getSource()).stop();
            }
        });
        timerContador.start();
    }
   

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuizViaLactea1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAyuda;
    private javax.swing.JButton jBtnLuna;
    private javax.swing.JButton jBtnPuntos;
    private javax.swing.JButton jBtnSaturno;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JButton jBtnSol;
    private javax.swing.JButton jBtnViaLactea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
