/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

/**
 *
 * @author sayuri
 */
public class Quiz_Origen extends javax.swing.JFrame {

    private void aplicarAnimacion(javax.swing.JButton boton) {
        int originalY = boton.getY();

        boton.setLocation(boton.getX(), originalY + 5);

        javax.swing.Timer timer = new javax.swing.Timer(100, e -> {
            boton.setLocation(boton.getX(), originalY);
            boton.repaint();
        });

        timer.setRepeats(false);
        timer.start();
    }
    private javax.swing.JPanel panelError;


    private boolean respuestaCorrecta = false;
    private int vidas = 3; // Contador de vidas iniciales
    private javax.swing.JPanel panelMensaje; // Ventana personalizada de "Excelente"
    private javax.swing.JLabel labelVidas; // Texto que muestra las vidas en pantalla
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_Origen.class.getName());


    /**
     * Creates new form Quiz_Origen
     */
    public Quiz_Origen() {
        initComponents();
        this.setLocationRelativeTo(null);
// Agrega esto en el constructor Quiz_Origen()
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });
        
           this.setLocationRelativeTo(null);
        
        // Inicializar interfaz de vidas y ventanas emergentes
        crearPanelMensajePersonalizado();
        crearIndicadorVidas();
        
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });
        
                crearPanelErrorPersonalizado(); 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        muñeco = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/button A (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, 50, 50));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Teoría del estado estacionario.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 320, 30));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Botton B.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, 50, 50));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton C.png"))); // NOI18N
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, 50, 50));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("Teoría del Big Bang.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 450, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Universo eléctrico.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 530, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("1. ¿Cuál es la teoría más aceptada sobre el origen del universo? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 560, 50));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton Siguiente1.png"))); // NOI18N
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(this::jButton4ActionPerformed);
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 570, 100, 60));

        muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñeco_correcto.png"))); // NOI18N
        muñeco.setRequestFocusEnabled(false);
        getContentPane().add(muñeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 340, 200, 230));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo Quiz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 870, 791));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

          aplicarAnimacion(jButton1);
        
        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            vidas--; // Resta una vida
            actualizarMarcadorVidas(); // Actualiza los corazones
            
            if (vidas > 0) {
                panelError.setVisible(true); // Muestra la ventana ROJA de error
            }
        });
        delayTimer.setRepeats(false);
        delayTimer.start();
           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

      aplicarAnimacion(jButton2);
        respuestaCorrecta = true; // Marcamos que la respuesta es la correcta
        
        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            try {
                // Le agregué el ".png" al final para que Java encuentre tu archivo
                muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñequitolike.png"))); 
            } catch(Exception ex) {
                logger.log(java.util.logging.Level.WARNING, "No se encontró la imagen del muñeco like");
            }
            panelMensaje.setVisible(true); // Hace aparecer el aviso VERDE de ¡EXCELENTE!
        });
        delayTimer.setRepeats(false);
        delayTimer.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
  
         aplicarAnimacion(jButton3);

        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            vidas--; // Resta una vida
            actualizarMarcadorVidas(); // Actualiza los corazones
            
            if (vidas > 0) {
                panelError.setVisible(true); // Muestra la ventana ROJA de error
            }
        });
        delayTimer.setRepeats(false);
        delayTimer.start();
    
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (respuestaCorrecta) {
        // Aquí llamas a tu siguiente formulario (ejemplo: Quiz_Dos)
        Quiz_Origen2 siguiente = new Quiz_Origen2();
        siguiente.setVisible(true);
        this.dispose(); // Cierra el formulario actual
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debes responder correctamente.");
    }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quiz_Origen().setVisible(true));
    }

    private void procesarError() {
        GameData.restarVida();

        if (GameData.vidas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No es el correcto. Te quedan " + GameData.vidas + " vidas.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Game Over! Has perdido todas tus vidas.");
            System.exit(0); // Cierra el programa
        }
    }
    
        private void crearIndicadorVidas() {
        labelVidas = new javax.swing.JLabel("VIDAS: ❤️ ❤️ ❤️");
        labelVidas.setFont(new java.awt.Font("Rockwell Extra Bold", java.awt.Font.BOLD, 16));
        labelVidas.setForeground(java.awt.Color.RED);
        // Coloca el marcador arriba a la derecha de la ventana
        getContentPane().add(labelVidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 20, 160, 30));
        // Forzar orden visual sobre el fondo
        getContentPane().setComponentZOrder(labelVidas, 0); 
    }

    private void crearPanelMensajePersonalizado() {
        panelMensaje = new javax.swing.JPanel();
        panelMensaje.setBackground(new java.awt.Color(34, 177, 76)); // Color verde exacto
        panelMensaje.setLayout(null);
        panelMensaje.setBounds(200, 320, 450, 250); // Centrado sobre el cuestionario
        panelMensaje.setVisible(false); // Oculto al inicio

        javax.swing.JLabel txt1 = new javax.swing.JLabel("¡WOW! ¡EXCELENTE!", javax.swing.SwingConstants.CENTER);
        txt1.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 24));
        txt1.setForeground(java.awt.Color.WHITE);
        txt1.setBounds(0, 30, 450, 40);
        panelMensaje.add(txt1);

        javax.swing.JLabel txt2 = new javax.swing.JLabel("✨ ¡CORRECTO! ✨", javax.swing.SwingConstants.CENTER);
        txt2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
        txt2.setForeground(java.awt.Color.YELLOW);
        txt2.setBounds(0, 85, 450, 30);
        panelMensaje.add(txt2);

        javax.swing.JButton btnContinuar = new javax.swing.JButton("¡CONTINUAR!");
        btnContinuar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        btnContinuar.setForeground(java.awt.Color.BLACK);
        btnContinuar.setBackground(java.awt.Color.WHITE);
        btnContinuar.setFocusPainted(false);
        btnContinuar.setBounds(125, 150, 200, 45);
        
        // Acción al hacer clic en ¡CONTINUAR!
        btnContinuar.addActionListener(e -> {
            panelMensaje.setVisible(false); // Oculta el cartel verde
            muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñequitolike.png"))); // Cambia pose a apuntar
            muñeco.repaint();
        });
        panelMensaje.add(btnContinuar);

        // Agregamos el panel flotante a la ventana principal
        getContentPane().add(panelMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 450, 250));
        getContentPane().setComponentZOrder(panelMensaje, 0); // Lo trae al frente de todo
    }

    private void actualizarMarcadorVidas() {
        if (vidas == 3) labelVidas.setText("VIDAS: ❤️ ❤️ ❤️");
        else if (vidas == 2) labelVidas.setText("VIDAS: ❤️ ❤️ 🖤");
        else if (vidas == 1) labelVidas.setText("VIDAS: ❤️ 🖤 🖤");
        else {
            labelVidas.setText("VIDAS: 🖤 🖤 🖤");
            javax.swing.JOptionPane.showMessageDialog(this, "¡Game Over! Te has quedado sin vidas.", "Fin del Juego", javax.swing.JOptionPane.ERROR_MESSAGE);
            // Aquí puedes reiniciar el juego creando un nuevo formulario o cerrándolo
            this.dispose();
        }
    }
    
    private void crearPanelErrorPersonalizado() {
        panelError = new javax.swing.JPanel();
        panelError.setBackground(new java.awt.Color(220, 53, 69)); // Color rojo
        panelError.setLayout(null);
        panelError.setBounds(200, 320, 450, 250); // Mismo tamaño y posición central
        panelError.setVisible(false); 

        javax.swing.JLabel txt1 = new javax.swing.JLabel("¡OOPS! TE EQUIVOCASTE", javax.swing.SwingConstants.CENTER);
        txt1.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 22));
        txt1.setForeground(java.awt.Color.WHITE);
        txt1.setBounds(0, 30, 450, 40);
        panelError.add(txt1);

        javax.swing.JLabel txt2 = new javax.swing.JLabel("❌ Respuesta Incorrecta ❌", javax.swing.SwingConstants.CENTER);
        txt2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
        txt2.setForeground(java.awt.Color.YELLOW);
        txt2.setBounds(0, 85, 450, 30);
        panelError.add(txt2);

        javax.swing.JButton btnReintentar = new javax.swing.JButton("INTENTAR DE NUEVO");
        btnReintentar.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
        btnReintentar.setForeground(java.awt.Color.BLACK);
        btnReintentar.setBackground(java.awt.Color.WHITE);
        btnReintentar.setFocusPainted(false);
        btnReintentar.setBounds(100, 150, 250, 45);
        
        // Al darle clic, solo se oculta el cartel rojo para dejarlo jugar otra vez
        btnReintentar.addActionListener(e -> {
            panelError.setVisible(false);
        });
        panelError.add(btnReintentar);

        getContentPane().add(panelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 450, 250));
        getContentPane().setComponentZOrder(panelError, 0); // Traer al frente
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel muñeco;
    // End of variables declaration//GEN-END:variables
}
