/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

/**
 *
 * @author sayuri
 */
public class Quiz_Planetas extends javax.swing.JFrame {

    private boolean respuestaCorrecta = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_Planetas.class.getName());

   private void animarGiro(javax.swing.JButton boton) {
    javax.swing.Timer timer = new javax.swing.Timer(20, null);
    final double[] angulo = {0};
    
    timer.addActionListener(e -> {
        angulo[0] += 0.2; // Velocidad de rotación
        boton.repaint(); // Solicita repintar para aplicar la transformación
        if (angulo[0] >= 6.28) { // Completa 360 grados (2*PI)
            timer.stop();
        }
    });
    
    // Sobrescribimos el método paintComponent para realizar la rotación
    boton.setUI(new javax.swing.plaf.basic.BasicButtonUI() {
        @Override
        public void paint(java.awt.Graphics g, javax.swing.JComponent c) {
            java.awt.Graphics2D g2 = (java.awt.Graphics2D) g.create();
            g2.rotate(angulo[0], c.getWidth() / 2, c.getHeight() / 2);
            super.paint(g2, c);
            g2.dispose();
        }
    });
    timer.start();
}
    /**
     * Creates new form Quiz_Planetas
     */
    public Quiz_Planetas() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jbtA = new javax.swing.JButton();
        jbtB = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtC = new javax.swing.JButton();
        jbtSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("1. ¿Cuáles son los planetas rocosos? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 400, 50));

        jbtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/button A (1).png"))); // NOI18N
        jbtA.setBorder(null);
        jbtA.setContentAreaFilled(false);
        jbtA.setFocusPainted(false);
        jbtA.setRequestFocusEnabled(false);
        jbtA.addActionListener(this::jbtAActionPerformed);
        getContentPane().add(jbtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 50, 50));

        jbtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Botton B.png"))); // NOI18N
        jbtB.setBorder(null);
        jbtB.setContentAreaFilled(false);
        jbtB.setFocusPainted(false);
        jbtB.setRequestFocusEnabled(false);
        jbtB.addActionListener(this::jbtBActionPerformed);
        getContentPane().add(jbtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 50, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel4.setText("Mercurio, Venus, Tierra y Marte.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel2.setText("Júpiter, Saturno, Urano y Neptuno.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, -1, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel3.setText("Saturno, Marte y Venus.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 460, 310, 40));

        jbtC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton C.png"))); // NOI18N
        jbtC.setBorder(null);
        jbtC.setBorderPainted(false);
        jbtC.setContentAreaFilled(false);
        jbtC.addActionListener(this::jbtCActionPerformed);
        getContentPane().add(jbtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 50, 50));

        jbtSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton Siguiente1.png"))); // NOI18N
        jbtSiguiente.setBorder(null);
        jbtSiguiente.setBorderPainted(false);
        jbtSiguiente.setContentAreaFilled(false);
        jbtSiguiente.addActionListener(this::jbtSiguienteActionPerformed);
        getContentPane().add(jbtSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo de las plantas (1).png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 690));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAActionPerformed
        // TODO add your handling code here:
        verificarRespuesta(true, jbtA); // A es el CORRECTO
    }//GEN-LAST:event_jbtAActionPerformed

    private void jbtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBActionPerformed
        // TODO add your handling code here:
        verificarRespuesta(false, jbtB);
    }//GEN-LAST:event_jbtBActionPerformed

    private void jbtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCActionPerformed
        // TODO add your handling code here:

        verificarRespuesta(false, jbtC);
    }//GEN-LAST:event_jbtCActionPerformed

    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        // TODO add your handling code here:
if (respuestaCorrecta) {
            // Aquí llamas a tu siguiente formulario (ejemplo: Quiz_Dos)
           Quiz_Planetas2 siguiente = new Quiz_Planetas2();
            siguiente.setVisible(true);
            this.dispose(); // Cierra el formulario actual
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debes responder correctamente.");
        }

    }//GEN-LAST:event_jbtSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quiz_Planetas().setVisible(true));
    }

    private void verificarRespuesta(boolean esCorrecto, javax.swing.JButton boton) {
        animarGiro(boton);

        if (esCorrecto) {
            respuestaCorrecta = true;
            javax.swing.JOptionPane.showMessageDialog(this, "¡Correcto!");
        } else {
            respuestaCorrecta = false;
            GameData.restarVida();
            if (GameData.vidas > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrecto. Te quedan " + GameData.vidas + " vidas.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Incorrecto! Game Over.");
                System.exit(0);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtA;
    private javax.swing.JButton jbtB;
    private javax.swing.JButton jbtC;
    private javax.swing.JButton jbtSiguiente;
    // End of variables declaration//GEN-END:variables
}
