/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import java.awt.Image;
import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Usuario
 */
public class QuizViaLactea extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(QuizViaLactea.class.getName());

    /**
     * Creates new form QuizViaLactea
     */
    public QuizViaLactea() {
        initComponents();
        try {
    java.net.URL urlSonido = getClass().getResource("/audio/BienvenidaLactea.wav");
    System.out.println("URL encontrada: " + urlSonido); // <-- linea nueva de diagnostico
    
    AudioInputStream audioStream = AudioSystem.getAudioInputStream(urlSonido);
    Clip clip = AudioSystem.getClip();
    clip.open(audioStream);
    clip.start();
            } catch (Exception e) {
    e.printStackTrace();
     }
        
    
         ResponsiveResizer resizer = new ResponsiveResizer(this);
         resizer.registerBackground(jLabelFondo);

         resizer.start();

    // --- Animacion del boton cohete: flota suavemente arriba y abajo ---
    final int posicionYOriginal = jBtnCohete.getY(); // guarda su posicion inicial
    final int amplitudPixeles = 10;   // que tanto sube y baja
    final double[] angulo = {0};     // usamos array para poder modificarlo dentro del lambda

    Timer timerCohete = new Timer(30, e -> {
        angulo[0] += 0.12;
        int offsetY = (int) (Math.sin(angulo[0]) * amplitudPixeles);
        jBtnCohete.setLocation(jBtnCohete.getX(), posicionYOriginal + offsetY);
    });
    timerCohete.start();
    
    // --- Animacion de zoom (respiracion) para el nino y la nina ---
final ImageIcon iconoNinoOriginal = (ImageIcon) jLabelNino.getIcon();
final ImageIcon iconoNinaOriginal = (ImageIcon) jLabelNina.getIcon();

final int anchoNinoBase = jLabelNino.getWidth();
final int altoNinoBase  = jLabelNino.getHeight();
final int anchoNinaBase = jLabelNina.getWidth();
final int altoNinaBase  = jLabelNina.getHeight();

final int centroXNino = jLabelNino.getX() + anchoNinoBase / 2;
final int centroYNino = jLabelNino.getY() + altoNinoBase / 2;
final int centroXNina = jLabelNina.getX() + anchoNinaBase / 2;
final int centroYNina = jLabelNina.getY() + altoNinaBase / 2;

final double[] anguloZoom = {0};
final double amplitudZoom = 0.06; // que tanto crece/achica (6%). Sube a 0.10 para mas notorio.

javax.swing.Timer timerZoom = new javax.swing.Timer(30, e -> {
    anguloZoom[0] += 0.08; // velocidad del pulso
    double factor = 1.0 + amplitudZoom * Math.sin(anguloZoom[0]);

    int wNino = (int) (anchoNinoBase * factor);
    int hNino = (int) (altoNinoBase * factor);
    Image escaladoNino = iconoNinoOriginal.getImage().getScaledInstance(wNino, hNino, Image.SCALE_SMOOTH);
    jLabelNino.setIcon(new ImageIcon(escaladoNino));
    jLabelNino.setBounds(centroXNino - wNino / 2, centroYNino - hNino / 2, wNino, hNino);

    int wNina = (int) (anchoNinaBase * factor);
    int hNina = (int) (altoNinaBase * factor);
    Image escaladoNina = iconoNinaOriginal.getImage().getScaledInstance(wNina, hNina, Image.SCALE_SMOOTH);
    jLabelNina.setIcon(new ImageIcon(escaladoNina));
    jLabelNina.setBounds(centroXNina - wNina / 2, centroYNina - hNina / 2, wNina, hNina);
});
timerZoom.start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNino = new javax.swing.JLabel();
        jLabelNina = new javax.swing.JLabel();
        jBtnCohete = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelNino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/NiñoViaLactea (1).png"))); // NOI18N
        jLabelNino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelNinoMouseClicked(evt);
            }
        });
        getContentPane().add(jLabelNino, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, 260, 250));

        jLabelNina.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/NiñaViaLactea1.png"))); // NOI18N
        getContentPane().add(jLabelNina, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 230, 280));

        jBtnCohete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/CoheteViaLactea (1).png"))); // NOI18N
        jBtnCohete.setBorderPainted(false);
        jBtnCohete.setContentAreaFilled(false);
        jBtnCohete.addActionListener(this::jBtnCoheteActionPerformed);
        getContentPane().add(jBtnCohete, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 430, 130, 360));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnAdelante.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 560, 100, 100));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Lactea1 (1).png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCoheteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCoheteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCoheteActionPerformed

    private void jLabelNinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelNinoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelNinoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new QuizViaLactea().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCohete;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelNina;
    private javax.swing.JLabel jLabelNino;
    // End of variables declaration//GEN-END:variables
}
