/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

/**
 *
 * @author sayuri
 */
public class Quiz_SistemaSolar3 extends javax.swing.JFrame {

    private boolean respuestaCorrecta = false;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_SistemaSolar3.class.getName());

    private void animarBoton(javax.swing.JButton boton) {
        java.awt.Color colorOriginal = boton.getBackground();
        // Cambiamos a un tono de azul suave
        boton.setBackground(new java.awt.Color(173, 216, 230));
        boton.setOpaque(true);
        boton.setContentAreaFilled(true); // Necesario para que el color sea visible

        javax.swing.Timer timer = new javax.swing.Timer(300, e -> {
            boton.setBackground(colorOriginal);
            boton.setContentAreaFilled(false); // Regresa a tu estilo transparente
            ((javax.swing.Timer) e.getSource()).stop();
        });
        timer.setRepeats(false);
        timer.start();
    }

    /**
     * Creates new form Quiz_SistemaSolar
     */
    public Quiz_SistemaSolar3() {
        initComponents();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jbtA = new javax.swing.JButton();
        jbtB = new javax.swing.JButton();
        jbtC = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtSiguiente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 13)); // NOI18N
        jLabel5.setText("3. ¿Hace cuánto tiempo se formó el Sistema Solar? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 400, 50));

        jbtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/button A (1).png"))); // NOI18N
        jbtA.setBorder(null);
        jbtA.setContentAreaFilled(false);
        jbtA.setFocusPainted(false);
        jbtA.setRequestFocusEnabled(false);
        jbtA.addActionListener(this::jbtAActionPerformed);
        getContentPane().add(jbtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 50, 50));

        jbtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Botton B.png"))); // NOI18N
        jbtB.setBorder(null);
        jbtB.setContentAreaFilled(false);
        jbtB.setFocusPainted(false);
        jbtB.setRequestFocusEnabled(false);
        jbtB.addActionListener(this::jbtBActionPerformed);
        getContentPane().add(jbtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 50, 50));

        jbtC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton C.png"))); // NOI18N
        jbtC.setBorder(null);
        jbtC.setBorderPainted(false);
        jbtC.setContentAreaFilled(false);
        jbtC.addActionListener(this::jbtCActionPerformed);
        getContentPane().add(jbtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 50, 50));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel4.setText("4 500 millones de años.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel2.setText("500 millones de años.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 410, -1, 30));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 15)); // NOI18N
        jLabel3.setText("100 millones de años.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 480, 160, 40));

        jbtSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton Siguiente1.png"))); // NOI18N
        jbtSiguiente.setBorder(null);
        jbtSiguiente.setBorderPainted(false);
        jbtSiguiente.setContentAreaFilled(false);
        jbtSiguiente.addActionListener(this::jbtSiguienteActionPerformed);
        getContentPane().add(jbtSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 510, 100, 60));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo Sistema Solar.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAActionPerformed
        // TODO add your handling code here:
        procesarRespuesta(true, jbtA);
    }//GEN-LAST:event_jbtAActionPerformed

    private void jbtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBActionPerformed
        // TODO add your handling code here:
        procesarRespuesta(false, jbtB);

    }//GEN-LAST:event_jbtBActionPerformed

    private void jbtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCActionPerformed
        // TODO add your handling code here:
        procesarRespuesta(false, jbtC);
    }//GEN-LAST:event_jbtCActionPerformed

    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        // TODO add your handling code here:
        
        if (respuestaCorrecta) {
            Quiz_SistemaSolar4 siguiente = new Quiz_SistemaSolar4();
            siguiente.setVisible(true);
            this.dispose(); 
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Primero debes responder correctamente.");
        }
      

    }//GEN-LAST:event_jbtSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quiz_SistemaSolar3().setVisible(true));

    }

  private void procesarRespuesta(boolean esCorrecto, javax.swing.JButton boton) {
        // Ejecutamos la animación de vibración
        animarBoton(boton);

        if (esCorrecto) {
            respuestaCorrecta = true;
            javax.swing.JOptionPane.showMessageDialog(this, "¡Correcto!");
        } else {
            respuestaCorrecta = false;
            // Solo restamos vida si es incorrecto
            GameData.restarVida();

            if (GameData.vidas > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Incorrecto. Te quedan " + GameData.vidas + " vidas.");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "¡Incorrecto! Has perdido todas tus vidas. Game Over.");
                System.exit(0);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtA;
    private javax.swing.JButton jbtB;
    private javax.swing.JButton jbtC;
    private javax.swing.JButton jbtSiguiente;
    // End of variables declaration//GEN-END:variables
}
