/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import javax.swing.ImageIcon;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author sayuri
 */
public class Quiz_Estacionario3 extends javax.swing.JFrame {

    private void aplicarAnimacion(javax.swing.JButton boton) {
        int originalY = boton.getY();

        boton.setLocation(boton.getX(), originalY + 5);

        javax.swing.Timer timer = new javax.swing.Timer(100, e -> {
            boton.setLocation(boton.getX(), originalY);
            boton.repaint();
        });

        timer.setRepeats(false);
        timer.start();
    }
    private javax.swing.JPanel panelError;

    private boolean respuestaCorrecta = false;
    private boolean pistaUsada = false;

    private javax.swing.JPanel panelMensaje; // Ventana personalizada de "Excelente"
    private javax.swing.JPanel panelPista;
    private javax.swing.JLabel lblTextoPista; // 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_Estacionario3.class.getName());

    /**
     * Creates new form Quiz_Origen
     */
    public Quiz_Estacionario3() {
        initComponents();
        
        this.setLocationRelativeTo(null);

        Sonido.reproducirMusica("musica_espacio.wav", -15.0f);

        lblPuntos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPuntos.setVerticalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPuntos.setForeground(java.awt.Color.WHITE);

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_pensando.png")));

        // Crear ventanas emergentes personalizadas
        crearPanelMensajePersonalizado();
        crearPanelErrorPersonalizado();
        crearPanelPistaPersonalizado();

        actualizarPuntos();
        jButton5.setEnabled(false);

        habilitarOpciones();
        pistaUsada = false;
        btnPista.setEnabled(true);
        this.setLocationRelativeTo(null);

        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });
    }

    private void actualizarPuntos() {
        lblPuntos.setText(String.valueOf(GameData.puntos));
    }

    private void bloquearOpciones() {

        jButton1.setEnabled(false);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);

    }

    private void habilitarOpciones() {

        jButton1.setEnabled(true);
        jButton2.setEnabled(true);
        jButton3.setEnabled(true);

    }

    private void mostrarRespuestaCorrecta() {

        // Deshabilitamos solamente las incorrectas
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);

        // La correcta sigue activa y con su color normal
        jButton1.setEnabled(true);

        // Para evitar que vuelvan a darle clic
        if (jButton1.getActionListeners().length > 0) {
            jButton1.removeActionListener(jButton1.getActionListeners()[0]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnPista = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblPuntos = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        muñeco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/opccionA.png"))); // NOI18N
        jButton1.setText("Porque el universo se expande");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 460, 70));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/opccionB.png"))); // NOI18N
        jButton2.setText("Porque dejaron de existir las estrellas");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 410, 460, 70));

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/opccionC.png"))); // NOI18N
        jButton3.setText("Porque la Luna desapareció");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.addActionListener(this::jButton3ActionPerformed);
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 480, 480, 70));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("1.¿Por qué esta teoría perdió fuerza? ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 350, 50));

        btnPista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pista.png"))); // NOI18N
        btnPista.setText("PISTA");
        btnPista.setBorderPainted(false);
        btnPista.setContentAreaFilled(false);
        btnPista.addActionListener(this::btnPistaActionPerformed);
        getContentPane().add(btnPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 540, 150, 90));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btn_sgte.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 550, -1, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/astro_pensando.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, -1, -1));

        lblPuntos.setBackground(new java.awt.Color(255, 255, 255));
        lblPuntos.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        lblPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/puntos.png"))); // NOI18N
        getContentPane().add(lblPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 140, 80));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("10");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 50, 20));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pregunta 1 de 3 ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 150, 30));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/panel.preg.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 430, 150));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo Quiz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 890, 791));

        muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñeco_correcto.png"))); // NOI18N
        muñeco.setRequestFocusEnabled(false);
        getContentPane().add(muñeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 200, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        aplicarAnimacion(jButton1);

        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            respuestaCorrecta();
        });

        delayTimer.setRepeats(false);
        delayTimer.start();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        aplicarAnimacion(jButton2);

        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            respuestaIncorrecta();
        });

        delayTimer.setRepeats(false);
        delayTimer.start();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        aplicarAnimacion(jButton3);

        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
            respuestaIncorrecta();
        });

        delayTimer.setRepeats(false);
        delayTimer.start();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPistaActionPerformed
        // TODO add your handling code here:

        if (respuestaCorrecta) {
            return;
        }

        if (!pistaUsada) {
            Sonido.reproducir("idea.wav");
            GameData.restarPuntos();
            actualizarPuntos();
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_sorpresa.png")));

            //texto para la pista
            setPistaTexto("Los científicos observaron que las galaxias se alejan unas de otras.");

            // Muestra tu panel personalizado con la imagen idea_pista.png
            panelPista.setVisible(true);

            pistaUsada = true;
            btnPista.setEnabled(false);

        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya utilizaste la pista."
            );
        }
    }//GEN-LAST:event_btnPistaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Sonido.reproducir("next.wav");
        Resultado_Estacionario siguiente = new Resultado_Estacionario();
        
        siguiente.setLocation(this.getLocation());
        
        siguiente.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quiz_Estacionario3().setVisible(true));
    }
//respuesta correcta

    private void respuestaCorrecta() {

        respuestaCorrecta = true;

        GameData.sumarPuntos();
        Sonido.reproducir("correcto.wav");
        actualizarPuntos();

        jButton5.setEnabled(true);
        mostrarRespuestaCorrecta();

        try {
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_celebra.png")));
        } catch (Exception ex) {
            logger.log(Level.WARNING, "No se encontró la imagen.");
        }

        panelMensaje.setVisible(true);
    }

    private void respuestaIncorrecta() {

        GameData.restarPuntos();
        Sonido.reproducir("error.wav");
        actualizarPuntos();

        jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_triste.png")));

        panelError.setVisible(true);
    }

    private void crearPanelMensajePersonalizado() {
        panelMensaje = new javax.swing.JPanel();
        panelMensaje.setLayout(null);
        panelMensaje.setOpaque(false);

        // 🟢 1. Tamaño total del área emergente (más alto para albergar el botón abajo)
        int ancho = 520;
        int alto = 220;

        // Posicionamos el panel completo un poco más arriba para centrarlo (Y: 210)
        panelMensaje.setBounds(150, 245, ancho, alto);
        panelMensaje.setVisible(false);

        // 🟢 2. Fondo semitransparente (Oscurece lo que está detrás para dar efecto emergente)
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel();
        fondoOscuro.setBackground(new java.awt.Color(0, 0, 0, 190)); // Negro con transparencia (alpha 150)
        fondoOscuro.setBounds(0, 0, ancho, alto);
        // Para bordes redondeados bonitos detrás del cartel
        fondoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 80), 2, true));

        // 🟢 3. Botón "CONTINUAR" dentro del área visible
        javax.swing.JButton btnContinuar = new javax.swing.JButton("¡CONTINUAR!");
        btnContinuar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnContinuar.setForeground(java.awt.Color.WHITE);
        btnContinuar.setBackground(new java.awt.Color(40, 167, 69)); // Verde limpio brillante
        btnContinuar.setFocusPainted(false);
        btnContinuar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Y = 165 ubica el botón justo debajo de la imagen verde sin cortarse
        btnContinuar.setBounds(175, 165, 170, 38);

        btnContinuar.addActionListener(e -> {
            panelMensaje.setVisible(false);
            muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñequitolike.png")));
            muñeco.repaint();
        });

        // 🟢 4. Imagen verde del mensaje (alto: 150)
        javax.swing.JLabel fondoVerde = new javax.swing.JLabel();
        java.net.URL url = getClass().getResource("/imagen/rpta. correcta.png");

        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            java.awt.Image img = icon.getImage().getScaledInstance(ancho, 150, java.awt.Image.SCALE_SMOOTH);
            fondoVerde.setIcon(new ImageIcon(img));
        }
        fondoVerde.setBounds(0, 0, ancho, 150);

        // 🟢 5. Agregar componentes en ORDEN DE CAPAS (Arriba -> Abajo)
        panelMensaje.add(btnContinuar);  // Capa superior: Botón
        panelMensaje.add(fondoVerde);    // Capa media: Imagen verde
        panelMensaje.add(fondoOscuro);   // Capa inferior: Sombra oscura

        // 🟢 6. Agregar al contenedor principal
        getContentPane().add(panelMensaje,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 245, ancho, alto));

        getContentPane().setComponentZOrder(panelMensaje, 0);
    }

    private void crearPanelErrorPersonalizado() {
        panelError = new javax.swing.JPanel();
        panelError.setLayout(null);
        panelError.setOpaque(false);

        int ancho = 500;
        int alto = 220;

        // 🟢 1. Posición centrada idéntica al mensaje correcto
        panelError.setBounds(150, 245, ancho, alto);
        panelError.setVisible(false);

        // 🟢 2. Fondo semitransparente oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel();
        fondoOscuro.setBackground(new java.awt.Color(0, 0, 0, 210));
        fondoOscuro.setBounds(0, 0, ancho, alto);
        fondoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 100), 2, true));

        // 🟢 3. Botón "INTENTAR DE NUEVO" (Estilo Rojo/Reintento)
        javax.swing.JButton btnReintentar = new javax.swing.JButton("INTENTAR DE NUEVO");
        btnReintentar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        btnReintentar.setForeground(java.awt.Color.WHITE);
        btnReintentar.setBackground(new java.awt.Color(220, 53, 69)); // Rojo atractivo
        btnReintentar.setFocusPainted(false);
        btnReintentar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReintentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Posicionamos el botón centrado dentro del recuadro
        btnReintentar.setBounds(150, 165, 200, 38);

        btnReintentar.addActionListener(e -> {
            panelError.setVisible(false);
            jLabel3.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_pensando.png")));
        });

        // 🟢 4. Carga e imagen escalada del cartel rojo/incorrecto
        // Recuerda que en tu carpeta el archivo no tiene espacio: /imagen/rpta.incorrecto.png
        javax.swing.JLabel fondoRojo = new javax.swing.JLabel();
        java.net.URL url = getClass().getResource("/imagen/rpta.incorrecto.png");

        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            java.awt.Image img = icon.getImage().getScaledInstance(ancho, 150, java.awt.Image.SCALE_SMOOTH);
            fondoRojo.setIcon(new ImageIcon(img));
        }
        fondoRojo.setBounds(0, 0, ancho, 150);

        // 🟢 5. Agregar en orden de capas (Botón -> Imagen -> Sombra)
        panelError.add(btnReintentar);
        panelError.add(fondoRojo);
        panelError.add(fondoOscuro);

        // 🟢 6. Agregar al AbsoluteLayout de la ventana
        getContentPane().add(panelError,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 245, ancho, alto));

        getContentPane().setComponentZOrder(panelError, 0);
    }

    private void crearPanelPistaPersonalizado() {
        panelPista = new javax.swing.JPanel();
        panelPista.setLayout(null);
        panelPista.setOpaque(false);

        // 1. Usar el tamaño real proporcional de tu imagen
        int ancho = 630;
        int alto = 142;

        // Posicionamos el panel centrado 
        panelPista.setBounds(70, 385, ancho, alto);
        panelPista.setVisible(false);

        // 2. Texto ajustado SOLO al espacio azul del centro (entre el foco y el astronauta)
        lblTextoPista = new javax.swing.JLabel("", javax.swing.SwingConstants.CENTER);
        lblTextoPista.setFont(new java.awt.Font("Sitka Text", java.awt.Font.BOLD, 17));
        lblTextoPista.setForeground(java.awt.Color.WHITE); // Texto blanco para que resalte en el azul

        // X: 160 deja espacio libre al foco a la izquierda y al astronauta a la derecha
        lblTextoPista.setBounds(180, 57, 260, 65);
        panelPista.add(lblTextoPista);

        // 3. Botón invisible de cerrar (que cubra toda la imagen para cerrar al hacer clic)
        javax.swing.JButton btnCerrar = new javax.swing.JButton();
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setBounds(0, 0, ancho, alto); // Si hacen clic en cualquier parte del cartel, se cierra
        btnCerrar.addActionListener(e -> panelPista.setVisible(false));
        panelPista.add(btnCerrar);

        // 4. Imagen de fondo respetando su aspecto original
        javax.swing.JLabel imagenFondo = new javax.swing.JLabel();
        java.net.URL urlImg = getClass().getResource("/imagen/idea_pista.png");

        if (urlImg != null) {
            ImageIcon iconOriginal = new ImageIcon(urlImg);
            java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
            imagenFondo.setIcon(new ImageIcon(imgEscalada));
        }
        imagenFondo.setBounds(0, 0, ancho, alto);

        // Se agrega al fondo del panel
        panelPista.add(imagenFondo);

        // Agregar al AbsoluteLayout con las dimensiones correctas
        getContentPane().add(panelPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 385, ancho, alto));
        getContentPane().setComponentZOrder(panelPista, 0);
    }

    private void setPistaTexto(String texto) {
        if (lblTextoPista != null) {
            // Añadimos el formato HTML con texto blanco y centrado
            lblTextoPista.setText("<html><div style='text-align: center; color: white;'>" + texto + "</div></html>");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPista;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel muñeco;
    // End of variables declaration//GEN-END:variables

}
