/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

/**
 *
 * @author sayuri
 */
public class Quiz_Origen6 extends javax.swing.JFrame {

    private void aplicarAnimacion(javax.swing.JButton boton) {
        // Guarda el tamaño original
        java.awt.Dimension originalSize = boton.getSize();

        // Aumenta el tamaño ligeramente (Efecto zoom)
        boton.setSize(originalSize.width + 10, originalSize.height + 10);

        // Timer para restaurar el tamaño original
        javax.swing.Timer timer = new javax.swing.Timer(100, e -> {
            boton.setSize(originalSize);
            boton.repaint();
        });

        timer.setRepeats(false);
        timer.start();
    }

    private boolean respuestaCorrecta = false;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_Origen6.class.getName());

    /**
     * Creates new form Quiz_Origen
     */
    public Quiz_Origen6() {
        initComponents();
        this.setLocationRelativeTo(null);
// Agrega esto en el constructor Quiz_Origen()
        jbtA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jbtA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtA = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jbtB = new javax.swing.JButton();
        jbtC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/button A (1).png"))); // NOI18N
        jbtA.setBorder(null);
        jbtA.setContentAreaFilled(false);
        jbtA.setFocusPainted(false);
        jbtA.setRequestFocusEnabled(false);
        jbtA.addActionListener(this::jbtAActionPerformed);
        getContentPane().add(jbtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 50, 50));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Que el universo nunca cambia.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 420, 30));

        jbtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Botton B.png"))); // NOI18N
        jbtB.setBorder(null);
        jbtB.setContentAreaFilled(false);
        jbtB.setFocusPainted(false);
        jbtB.setRequestFocusEnabled(false);
        jbtB.addActionListener(this::jbtBActionPerformed);
        getContentPane().add(jbtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 430, 50, 50));

        jbtC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton C.png"))); // NOI18N
        jbtC.setBorder(null);
        jbtC.setBorderPainted(false);
        jbtC.setContentAreaFilled(false);
        jbtC.addActionListener(this::jbtCActionPerformed);
        getContentPane().add(jbtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 50, 50));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("Que solo existe una galaxia.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Que existen infinitos ciclos llamados eones.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("6. ¿Qué plantea la cosmología cíclica conforme? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 450, 50));

        jbtSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton Siguiente1.png"))); // NOI18N
        jbtSiguiente.setBorder(null);
        jbtSiguiente.setBorderPainted(false);
        jbtSiguiente.setContentAreaFilled(false);
        jbtSiguiente.addActionListener(this::jbtSiguienteActionPerformed);
        getContentPane().add(jbtSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 540, 100, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo Quiz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -40, 870, 791));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAActionPerformed
        // TODO add your handling code here:
        aplicarAnimacion(jbtA);
        respuestaCorrecta = false;
        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> procesarError());
        delayTimer.setRepeats(false);
        delayTimer.start();
    }//GEN-LAST:event_jbtAActionPerformed

    private void jbtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBActionPerformed
        // TODO add your handling code here:

        aplicarAnimacion(jbtB);
        respuestaCorrecta = false;
        javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> procesarError());
        delayTimer.setRepeats(false);
        delayTimer.start();
    }//GEN-LAST:event_jbtBActionPerformed

    private void jbtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCActionPerformed
        // TODO add your handling code here:

      aplicarAnimacion(jbtC);
    
    respuestaCorrecta = true; 
    
    javax.swing.Timer delayTimer = new javax.swing.Timer(200, e -> {
        javax.swing.JOptionPane.showMessageDialog(this, "¡Excelente!");
    });
    delayTimer.setRepeats(false);
    delayTimer.start();
    }//GEN-LAST:event_jbtCActionPerformed

    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_jbtSiguienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(() -> new Quiz_Origen6().setVisible(true));
    }

    private void procesarError() {
        GameData.restarVida();

        if (GameData.vidas > 0) {
            javax.swing.JOptionPane.showMessageDialog(this, "No es el correcto. Te quedan " + GameData.vidas + " vidas.");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Game Over! Has perdido todas tus vidas.");
            System.exit(0); // Cierra el programa
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtA;
    private javax.swing.JButton jbtB;
    private javax.swing.JButton jbtC;
    private javax.swing.JButton jbtSiguiente;
    // End of variables declaration//GEN-END:variables
}
