/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

/**
 *
 * @author sayuri
 */
public class Quiz_Láctea5 extends javax.swing.JFrame {
    
    private boolean respuestaCorrecta = false;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Quiz_Láctea5.class.getName());

    private void animarZoom(javax.swing.JButton boton, boolean entrar) {
        java.awt.Dimension original = new java.awt.Dimension(50, 50); // Tamaño base
        if (entrar) {
            boton.setSize(60, 60); // Aumenta tamaño
        } else {
            boton.setSize(original); // Vuelve al original
        }
    }
    
    /**
     * Creates new form Quez_Láctea
     */
    public Quiz_Láctea5() {
        initComponents();
        this.setLocationRelativeTo(null);
        configurarAnimaciones();
    }
    
    private void configurarAnimaciones() {
        javax.swing.JButton[] botones = {jbtA, jbtB, jbtC};
        for (javax.swing.JButton b : botones) {
            b.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseEntered(java.awt.event.MouseEvent evt) { animarZoom(b, true); }
                public void mouseExited(java.awt.event.MouseEvent evt) { animarZoom(b, false); }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtSiguiente = new javax.swing.JButton();
        jbtA = new javax.swing.JButton();
        jbtB = new javax.swing.JButton();
        jbtC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton Siguiente1.png"))); // NOI18N
        jbtSiguiente.setBorder(null);
        jbtSiguiente.setBorderPainted(false);
        jbtSiguiente.setContentAreaFilled(false);
        jbtSiguiente.addActionListener(this::jbtSiguienteActionPerformed);
        getContentPane().add(jbtSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 550, 100, 60));

        jbtA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/button A (1).png"))); // NOI18N
        jbtA.setBorder(null);
        jbtA.setContentAreaFilled(false);
        jbtA.setFocusPainted(false);
        jbtA.setRequestFocusEnabled(false);
        jbtA.addActionListener(this::jbtAActionPerformed);
        getContentPane().add(jbtA, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 50, 50));

        jbtB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Botton B.png"))); // NOI18N
        jbtB.setBorder(null);
        jbtB.setContentAreaFilled(false);
        jbtB.setFocusPainted(false);
        jbtB.setRequestFocusEnabled(false);
        jbtB.addActionListener(this::jbtBActionPerformed);
        getContentPane().add(jbtB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 50, 50));

        jbtC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botton C.png"))); // NOI18N
        jbtC.setBorder(null);
        jbtC.setBorderPainted(false);
        jbtC.setContentAreaFilled(false);
        jbtC.addActionListener(this::jbtCActionPerformed);
        getContentPane().add(jbtC, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, 50, 50));

        jLabel5.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 14)); // NOI18N
        jLabel5.setText("5. ¿Cuál es la parte más externa de la Vía Láctea? ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 440, 50));

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("Disco galáctico.");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 140, 40));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("Halo galáctico.");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 430, -1, 30));

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Bulbo central.");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondo Láctea.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 870, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSiguienteActionPerformed
        // TODO add your handling code here:
     
              if (respuestaCorrecta) {
        // Aquí llamas a tu siguiente formulario (ejemplo: Quiz_Dos)
        Quiz_Láctea6 siguiente = new Quiz_Láctea6();
        siguiente.setVisible(true);
        this.dispose(); // Cierra el formulario actual
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Primero debes responder correctamente.");
    }
        
        
    }//GEN-LAST:event_jbtSiguienteActionPerformed

    private void jbtAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtAActionPerformed
        // TODO add your handling code here:
     respuestaCorrecta = false;
    procesarError();
    }//GEN-LAST:event_jbtAActionPerformed

    private void jbtBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtBActionPerformed
        // TODO add your handling code here:
respuestaCorrecta = true;
    javax.swing.JOptionPane.showMessageDialog(this, "¡Correcto!");
      
    }//GEN-LAST:event_jbtBActionPerformed

    private void jbtCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCActionPerformed
        // TODO add your handling code here:

     respuestaCorrecta = false;
    procesarError();

    }//GEN-LAST:event_jbtCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Quiz_Láctea5().setVisible(true));
    }
    
    private void procesarError() {
    GameData.restarVida();
    if (GameData.vidas > 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Incorrecto. Te quedan " + GameData.vidas + " vidas.");
    } else {
        javax.swing.JOptionPane.showMessageDialog(this, "Game Over.");
        System.exit(0);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtA;
    private javax.swing.JButton jbtB;
    private javax.swing.JButton jbtC;
    private javax.swing.JButton jbtSiguiente;
    // End of variables declaration//GEN-END:variables
}
