/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import javax.swing.ImageIcon;
import java.util.logging.Level;
import javax.swing.JOptionPane;

/**
 *
 * @author sayuri
 */
public class Resultado_Estacionario extends javax.swing.JFrame {

    private void aplicarAnimacion(javax.swing.JButton boton) {
        int originalY = boton.getY();

        boton.setLocation(boton.getX(), originalY + 5);

        javax.swing.Timer timer = new javax.swing.Timer(100, e -> {
            boton.setLocation(boton.getX(), originalY);
            boton.repaint();
        });

        timer.setRepeats(false);
        timer.start();
    }
    private javax.swing.JPanel panelError;

    private boolean respuestaCorrecta = false;
    private boolean pistaUsada = false;

    private javax.swing.JPanel panelMensaje; // Ventana personalizada de "Excelente"
    private javax.swing.JPanel panelPista;
    private javax.swing.JLabel lblTextoPista; // 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Resultado_Estacionario.class.getName());

    /**
     * Creates new form Quiz_Origen
     */
    public Resultado_Estacionario() {
        initComponents();

        Sonido.detenerMusica();
        Sonido.reproducirMusica("victoria.wav", -10.0f);

        mostrarResultado();
        actualizarEstrellas();
        lblAstro.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_celebra.png")));

        // Crear ventanas emergentes personalizadas
        crearPanelMensajePersonalizado();
        crearPanelErrorPersonalizado();
        crearPanelPistaPersonalizado();

        jButton5.setEnabled(true);
    }

    private void mostrarResultado() {
        lblResultado.setText(GameData.puntos + " ");
    }

    private void actualizarEstrellas() {

        ImageIcon llena = new ImageIcon(getClass().getResource("/imagen/estrella_llena.png"));
        ImageIcon vacia = new ImageIcon(getClass().getResource("/imagen/estrella_vacia.png"));

        lblEstrella1.setIcon(vacia);
        lblEstrella2.setIcon(vacia);
        lblEstrella3.setIcon(vacia);

        if (GameData.puntos >= 10) {
            lblEstrella1.setIcon(llena);
        }

        if (GameData.puntos >= 25) {
            lblEstrella2.setIcon(llena);
        }

        if (GameData.puntos >= 35) {
            lblEstrella3.setIcon(llena);
        }

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton5 = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        lblAstro = new javax.swing.JLabel();
        lblEstrella1 = new javax.swing.JLabel();
        lblEstrella2 = new javax.swing.JLabel();
        lblEstrella3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        muñeco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btn_Menu.png"))); // NOI18N
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(this::jButton5ActionPerformed);
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 630, 260, 70));

        lblResultado.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        getContentPane().add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 70, 50));

        lblAstro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/astro_celebra.png"))); // NOI18N
        getContentPane().add(lblAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        lblEstrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estrella_vacia.png"))); // NOI18N
        getContentPane().add(lblEstrella1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 540, 110, 100));

        lblEstrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estrella_vacia.png"))); // NOI18N
        getContentPane().add(lblEstrella2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 530, -1, 110));

        lblEstrella3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/estrella_vacia.png"))); // NOI18N
        getContentPane().add(lblEstrella3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, 110, 110));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/puntaje.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 460, 270, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/resultado_panel3.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 710, 510));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("10");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 110, 50, 20));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pregunta 1 de 3 ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 150, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Fondo Quiz.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -30, 890, 791));

        muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñeco_correcto.png"))); // NOI18N
        muñeco.setRequestFocusEnabled(false);
        getContentPane().add(muñeco, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 340, 200, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Sonido.reproducir("next.wav");
        Sonido.detenerMusica();
        teoria_Origen siguiente = new teoria_Origen();
        siguiente.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Resultado_Estacionario().setVisible(true));
    }
//respuesta correcta

    private void crearPanelMensajePersonalizado() {
        panelMensaje = new javax.swing.JPanel();
        panelMensaje.setLayout(null);
        panelMensaje.setOpaque(false);

        // 🟢 1. Tamaño total del área emergente (más alto para albergar el botón abajo)
        int ancho = 520;
        int alto = 220;

        // Posicionamos el panel completo un poco más arriba para centrarlo (Y: 210)
        panelMensaje.setBounds(150, 245, ancho, alto);
        panelMensaje.setVisible(false);

        // 🟢 2. Fondo semitransparente (Oscurece lo que está detrás para dar efecto emergente)
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel();
        fondoOscuro.setBackground(new java.awt.Color(0, 0, 0, 190)); // Negro con transparencia (alpha 150)
        fondoOscuro.setBounds(0, 0, ancho, alto);
        // Para bordes redondeados bonitos detrás del cartel
        fondoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 80), 2, true));

        // 🟢 3. Botón "CONTINUAR" dentro del área visible
        javax.swing.JButton btnContinuar = new javax.swing.JButton("¡CONTINUAR!");
        btnContinuar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));
        btnContinuar.setForeground(java.awt.Color.WHITE);
        btnContinuar.setBackground(new java.awt.Color(40, 167, 69)); // Verde limpio brillante
        btnContinuar.setFocusPainted(false);
        btnContinuar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnContinuar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Y = 165 ubica el botón justo debajo de la imagen verde sin cortarse
        btnContinuar.setBounds(175, 165, 170, 38);

        btnContinuar.addActionListener(e -> {
            panelMensaje.setVisible(false);
            muñeco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/muñequitolike.png")));
            muñeco.repaint();
        });

        // 🟢 4. Imagen verde del mensaje (alto: 150)
        javax.swing.JLabel fondoVerde = new javax.swing.JLabel();
        java.net.URL url = getClass().getResource("/imagen/rpta. correcta.png");

        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            java.awt.Image img = icon.getImage().getScaledInstance(ancho, 150, java.awt.Image.SCALE_SMOOTH);
            fondoVerde.setIcon(new ImageIcon(img));
        }
        fondoVerde.setBounds(0, 0, ancho, 150);

        // 🟢 5. Agregar componentes en ORDEN DE CAPAS (Arriba -> Abajo)
        panelMensaje.add(btnContinuar);  // Capa superior: Botón
        panelMensaje.add(fondoVerde);    // Capa media: Imagen verde
        panelMensaje.add(fondoOscuro);   // Capa inferior: Sombra oscura

        // 🟢 6. Agregar al contenedor principal
        getContentPane().add(panelMensaje,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 245, ancho, alto));

        getContentPane().setComponentZOrder(panelMensaje, 0);
    }

    private void crearPanelErrorPersonalizado() {
        panelError = new javax.swing.JPanel();
        panelError.setLayout(null);
        panelError.setOpaque(false);

        int ancho = 500;
        int alto = 220;

        // 🟢 1. Posición centrada idéntica al mensaje correcto
        panelError.setBounds(150, 245, ancho, alto);
        panelError.setVisible(false);

        // 🟢 2. Fondo semitransparente oscuro
        javax.swing.JPanel fondoOscuro = new javax.swing.JPanel();
        fondoOscuro.setBackground(new java.awt.Color(0, 0, 0, 210));
        fondoOscuro.setBounds(0, 0, ancho, alto);
        fondoOscuro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255, 100), 2, true));

        // 🟢 3. Botón "INTENTAR DE NUEVO" (Estilo Rojo/Reintento)
        javax.swing.JButton btnReintentar = new javax.swing.JButton("INTENTAR DE NUEVO");
        btnReintentar.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 13));
        btnReintentar.setForeground(java.awt.Color.WHITE);
        btnReintentar.setBackground(new java.awt.Color(220, 53, 69)); // Rojo atractivo
        btnReintentar.setFocusPainted(false);
        btnReintentar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnReintentar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        // Posicionamos el botón centrado dentro del recuadro
        btnReintentar.setBounds(150, 165, 200, 38);

        btnReintentar.addActionListener(e -> {
            panelError.setVisible(false);
            lblAstro.setIcon(new ImageIcon(getClass().getResource("/imagen/astro_pensando.png")));
        });

        // 🟢 4. Carga e imagen escalada del cartel rojo/incorrecto
        // Recuerda que en tu carpeta el archivo no tiene espacio: /imagen/rpta.incorrecto.png
        javax.swing.JLabel fondoRojo = new javax.swing.JLabel();
        java.net.URL url = getClass().getResource("/imagen/rpta.incorrecto.png");

        if (url != null) {
            ImageIcon icon = new ImageIcon(url);
            java.awt.Image img = icon.getImage().getScaledInstance(ancho, 150, java.awt.Image.SCALE_SMOOTH);
            fondoRojo.setIcon(new ImageIcon(img));
        }
        fondoRojo.setBounds(0, 0, ancho, 150);

        // 🟢 5. Agregar en orden de capas (Botón -> Imagen -> Sombra)
        panelError.add(btnReintentar);
        panelError.add(fondoRojo);
        panelError.add(fondoOscuro);

        // 🟢 6. Agregar al AbsoluteLayout de la ventana
        getContentPane().add(panelError,
                new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 245, ancho, alto));

        getContentPane().setComponentZOrder(panelError, 0);
    }

    private void crearPanelPistaPersonalizado() {
        panelPista = new javax.swing.JPanel();
        panelPista.setLayout(null);
        panelPista.setOpaque(false);

        // 1. Usar el tamaño real proporcional de tu imagen
        int ancho = 630;
        int alto = 142;

        // Posicionamos el panel centrado 
        panelPista.setBounds(70, 385, ancho, alto);
        panelPista.setVisible(false);

        // 2. Texto ajustado SOLO al espacio azul del centro (entre el foco y el astronauta)
        lblTextoPista = new javax.swing.JLabel("", javax.swing.SwingConstants.CENTER);
        lblTextoPista.setFont(new java.awt.Font("Sitka Text", java.awt.Font.BOLD, 17));
        lblTextoPista.setForeground(java.awt.Color.WHITE); // Texto blanco para que resalte en el azul

        // X: 160 deja espacio libre al foco a la izquierda y al astronauta a la derecha
        lblTextoPista.setBounds(180, 57, 260, 65);
        panelPista.add(lblTextoPista);

        // 3. Botón invisible de cerrar (que cubra toda la imagen para cerrar al hacer clic)
        javax.swing.JButton btnCerrar = new javax.swing.JButton();
        btnCerrar.setBorder(null);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.setBounds(0, 0, ancho, alto); // Si hacen clic en cualquier parte del cartel, se cierra
        btnCerrar.addActionListener(e -> panelPista.setVisible(false));
        panelPista.add(btnCerrar);

        // 4. Imagen de fondo respetando su aspecto original
        javax.swing.JLabel imagenFondo = new javax.swing.JLabel();
        java.net.URL urlImg = getClass().getResource("/imagen/idea_pista.png");

        if (urlImg != null) {
            ImageIcon iconOriginal = new ImageIcon(urlImg);
            java.awt.Image imgEscalada = iconOriginal.getImage().getScaledInstance(ancho, alto, java.awt.Image.SCALE_SMOOTH);
            imagenFondo.setIcon(new ImageIcon(imgEscalada));
        }
        imagenFondo.setBounds(0, 0, ancho, alto);

        // Se agrega al fondo del panel
        panelPista.add(imagenFondo);

        // Agregar al AbsoluteLayout con las dimensiones correctas
        getContentPane().add(panelPista, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 385, ancho, alto));
        getContentPane().setComponentZOrder(panelPista, 0);
    }

    private void setPistaTexto(String texto) {
        if (lblTextoPista != null) {
            // Añadimos el formato HTML con texto blanco y centrado
            lblTextoPista.setText("<html><div style='text-align: center; color: white;'>" + texto + "</div></html>");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblAstro;
    private javax.swing.JLabel lblEstrella1;
    private javax.swing.JLabel lblEstrella2;
    private javax.swing.JLabel lblEstrella3;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel muñeco;
    // End of variables declaration//GEN-END:variables

}
