
package Astronomia;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class teoriaEstEst3 extends javax.swing.JFrame {
    
    private AstronautaController astro;
    private AudioController audio;
    
    public teoriaEstEst3() {
        
        initComponents();
        
        astro = new AstronautaController(jlabelAstro);
        astro.iniciar();  
        
        audio = new AudioController();
        reproducirNarracion("EstadoEst3.wav");
        
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/fondoEst3.png");
        //TRANSPARENCIA
        jbtnDesf.setContentAreaFilled(false);
        jbtnDesf.setBorderPainted(false);
        jbtnDesf.setOpaque(false);
        
        jbtnAnt1.setContentAreaFilled(false);
        jbtnAnt1.setBorderPainted(false);
        jbtnAnt1.setOpaque(false);
        
        jbtnFred.setContentAreaFilled(false);
        jbtnFred.setBorderPainted(false);
        jbtnFred.setOpaque(false);
        
        jbtnTho.setContentAreaFilled(false);
        jbtnTho.setBorderPainted(false);
        jbtnTho.setOpaque(false);
        
        jbtnHerm.setContentAreaFilled(false);
        jbtnHerm.setBorderPainted(false);
        jbtnHerm.setOpaque(false);
        
        EfectoBoton(jbtnDesf);
        EfectoBoton(jbtnAnt1);
        EfectoBoton(jbtnFred);
        EfectoBoton(jbtnTho);
        EfectoBoton(jbtnHerm);

        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnTho = new javax.swing.JButton();
        jbtnHerm = new javax.swing.JButton();
        jbtnFred = new javax.swing.JButton();
        jbtnDesf = new javax.swing.JButton();
        jbtnAnt1 = new javax.swing.JButton();
        jlabelAstro = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnTho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Thomas.png"))); // NOI18N
        jbtnTho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnThoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnTho, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, 230, 230));

        jbtnHerm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Hermann.png"))); // NOI18N
        jbtnHerm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHermActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHerm, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 230, 230));

        jbtnFred.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Fred.png"))); // NOI18N
        jbtnFred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnFredActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnFred, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 230, 230));

        jbtnDesf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonDesaf.png"))); // NOI18N
        jbtnDesf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDesfActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDesf, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 520, 250, 90));

        jbtnAnt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonAnterior.png"))); // NOI18N
        jbtnAnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnt1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 520, 210, 90));

        jlabelAstro.setText("jLabel1");
        jPanel1.add(jlabelAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 420));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoEst3.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        formulario_TemasAstro pantallaAstro = new formulario_TemasAstro();
        pantallaAstro.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnAnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnt1ActionPerformed
        teoriaEstEst2 conexAnt=new teoriaEstEst2();
        conexAnt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnAnt1ActionPerformed

    private void jbtnDesfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDesfActionPerformed
       //desafio
        Quiz_Estacionario1 siguiente = new Quiz_Estacionario1();
        siguiente.setVisible(true);

        this.dispose();
       
    }//GEN-LAST:event_jbtnDesfActionPerformed

    private void jbtnFredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnFredActionPerformed
        
    }//GEN-LAST:event_jbtnFredActionPerformed

    private void jbtnHermActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHermActionPerformed
        
    }//GEN-LAST:event_jbtnHermActionPerformed

    private void jbtnThoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnThoActionPerformed
       
    }//GEN-LAST:event_jbtnThoActionPerformed
    //función para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }    
    
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
    }
    
    public void reproducirNarracion(String archivo) {

        astro.empezarHablar();

        audio.reproducir("/audio/" + archivo, () -> {

            astro.dejarDeHablar();

        });

    }
    
    private void reproducirAudioBoton(String archivo) {

        audio.reproducir("/audio/" + archivo, null);

    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teoriaEstEst3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teoriaEstEst3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teoriaEstEst3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teoriaEstEst3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new teoriaEstEst3().setVisible(true);
        } // Variables declaration - do not modify
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAnt1;
    private javax.swing.JButton jbtnDesf;
    private javax.swing.JButton jbtnFred;
    private javax.swing.JButton jbtnHerm;
    private javax.swing.JButton jbtnTho;
    private javax.swing.JLabel jlabelAstro;
    // End of variables declaration//GEN-END:variables
}
