/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;


import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author User
 */
public class teoria_Origen extends javax.swing.JFrame {
    
    public teoria_Origen() {
        initComponents();
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/fondoTeoOrigen.png");
        
        //ajustar imagen a botón
        /*SetBotones(jbtnBigBang, "src/imagen/btnBigBang.png");
        SetBotones(jbtnBranas, "src/imagen/btnBranas.png");
        SetBotones(jbtnCiclica, "src/imagen/btnCiclica.png");
        SetBotones(jbtnElec, "src/imagen/btnElec.png");
        SetBotones(jbtnEst, "src/imagen/btnEst.png");
        SetBotones(jbtnRebote, "src/imagen/btnRebote.png");*/
        
        //transparencia a botón bigbang
        jbtnBigBang.setContentAreaFilled(false);
        jbtnBigBang.setBorderPainted(false);
        jbtnBigBang.setOpaque(false);
        //transparencia a botón branas
        jbtnBranas.setContentAreaFilled(false);
        jbtnBranas.setBorderPainted(false);
        jbtnBranas.setOpaque(false);
        //transparencia a botón cíclica
        jbtnCiclica.setContentAreaFilled(false);
        jbtnCiclica.setBorderPainted(false);
        jbtnCiclica.setOpaque(false);
        //transparencia a botón eléctrico
        jbtnElec.setContentAreaFilled(false);
        jbtnElec.setBorderPainted(false);
        jbtnElec.setOpaque(false);
        //transparencia a botón estacionario
        jbtnEst.setContentAreaFilled(false);
        jbtnEst.setBorderPainted(false);
        jbtnEst.setOpaque(false);
        //transparencia a botón rebote
        jbtnRebote.setContentAreaFilled(false);
        jbtnRebote.setBorderPainted(false);
        jbtnRebote.setOpaque(false);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnRebote = new javax.swing.JButton();
        jbtnEst = new javax.swing.JButton();
        jbtnElec = new javax.swing.JButton();
        jbtnCiclica = new javax.swing.JButton();
        jbtnBranas = new javax.swing.JButton();
        jbtnBigBang = new javax.swing.JButton();
        jlabelNave = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnRebote.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnRebote.png"))); // NOI18N
        jPanel1.add(jbtnRebote, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 160, 160));

        jbtnEst.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnEst.png"))); // NOI18N
        jPanel1.add(jbtnEst, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 160, 160));

        jbtnElec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnElec.png"))); // NOI18N
        jPanel1.add(jbtnElec, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 160, 170));

        jbtnCiclica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnCiclica.png"))); // NOI18N
        jbtnCiclica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCiclicaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCiclica, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 170, 160));

        jbtnBranas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnBranas.png"))); // NOI18N
        jbtnBranas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBranasActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBranas, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 160, 160));

        jbtnBigBang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnBigBang.png"))); // NOI18N
        jbtnBigBang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBigBangActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBigBang, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 170, 160));

        jlabelNave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/nave.png"))); // NOI18N
        jlabelNave.setText("jLabel1");
        jPanel1.add(jlabelNave, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 150, 260, 240));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 90, 90));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoTeoOrigen.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -20, 1030, 640));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        formulario_TemasAstro pantallaAstro = new formulario_TemasAstro();
        pantallaAstro.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnBigBangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBigBangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBigBangActionPerformed

    private void jbtnBranasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBranasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnBranasActionPerformed

    private void jbtnCiclicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCiclicaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCiclicaActionPerformed
    //método para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }
    //método para ajustar una imagen a un botón
    private void SetBotones(JButton ButonName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(ButonName.getWidth(), ButonName.getHeight(), Image.SCALE_DEFAULT));
        ButonName.setIcon(icon);
        this.repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teoria_Origen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teoria_Origen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teoria_Origen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teoria_Origen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teoria_Origen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnBigBang;
    private javax.swing.JButton jbtnBranas;
    private javax.swing.JButton jbtnCiclica;
    private javax.swing.JButton jbtnElec;
    private javax.swing.JButton jbtnEst;
    private javax.swing.JButton jbtnRebote;
    private javax.swing.JLabel jlabelNave;
    // End of variables declaration//GEN-END:variables
}
