/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Astronomia;

import formularios.*;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import matematica.formularios_Temas;

/**
 *
 * @author User
 */
public class teoria_SistSolar extends javax.swing.JFrame {
    
    public teoria_SistSolar() {
        initComponents();
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        
        
        //transparencia para el botón vía láctea
        jbtnSistemSolar.setOpaque(false);
        jbtnSistemSolar.setContentAreaFilled(false);
        jbtnSistemSolar.setBorderPainted(false);
        
        EfectoBoton(jbtnSistemSolar);
        
        //efecto boton para el ajuste
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnSistemSolar = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnSistemSolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnSistemaSolar.png"))); // NOI18N
        jbtnSistemSolar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSistemSolarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnSistemSolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 300, 400, 220));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoMundoAstro.jpg"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1030, 640));

        jButton1.setText("jButton1");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSistemSolarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSistemSolarActionPerformed
        formularios_Temas conexMundoMate = new formularios_Temas();
        conexMundoMate.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnSistemSolarActionPerformed

    
    //método para el efecto botón
    private void EfectoBoton(javax.swing.JButton boton) {
        if (boton.getIcon() == null) return;

        ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
        int anchoNormal = imgOriginal.getIconWidth();
        int altoNormal = imgOriginal.getIconHeight();

        // Calculamos las tres escalas:
        int anchoHover = (int) (anchoNormal * 1.08); // Un poco más grande (Hover)
        int altoHover = (int) (altoNormal * 1.08);

        int anchoClick = (int) (anchoNormal * 0.94); // Un poco más chico (Efecto hundido/presionado)
        int altoClick = (int) (altoNormal * 0.94);

        // Creamos los tres iconos escalados
        javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
        javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
        javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

        // Estética del botón
        boton.setContentAreaFilled(false);
        boton.setBorderPainted(false);
        boton.setFocusPainted(false);
        boton.setIcon(iconoNormal);

        // Control total de la ilusión de presión
        boton.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoHover); // Crece al pasar el mouse
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
            }

            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {
                boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
            }

            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {
                // Si sueltas el click dentro del botón, vuelve al tamaño hover
                if (boton.getBounds().contains(e.getPoint())) {
                    boton.setIcon(iconoHover);
                } else {
                    boton.setIcon(iconoNormal);
                }
            }
        });
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teoria_SistSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teoria_SistSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teoria_SistSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teoria_SistSolar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teoria_SistSolar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSistemSolar;
    // End of variables declaration//GEN-END:variables
}
