
package Astronomia;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
/**
 *
 * @author User
 */
public class teoriaBigBang3 extends javax.swing.JFrame {
    
    private AstronautaController astro;
    private AudioController audio;
    
    public teoriaBigBang3() {
        
        initComponents();
        
        astro = new AstronautaController(jlabelAstro);
        astro.iniciar();  
        
        audio = new AudioController();
        reproducirNarracion("BigBang3.wav");
        
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/fondoBigBang3.png");
        //TRANSPARENCIA
        jbtnDesf.setContentAreaFilled(false);
        jbtnDesf.setBorderPainted(false);
        jbtnDesf.setOpaque(false);
        
        jbtnAnt1.setContentAreaFilled(false);
        jbtnAnt1.setBorderPainted(false);
        jbtnAnt1.setOpaque(false);
        
        jbtnEins.setContentAreaFilled(false);
        jbtnEins.setBorderPainted(false);
        jbtnEins.setOpaque(false);
        
        jbtnHaw.setContentAreaFilled(false);
        jbtnHaw.setBorderPainted(false);
        jbtnHaw.setOpaque(false);
        
        jbtnHubb.setContentAreaFilled(false);
        jbtnHubb.setBorderPainted(false);
        jbtnHubb.setOpaque(false);
        
        jbtnHubb.setContentAreaFilled(false);
        jbtnHubb.setBorderPainted(false);
        jbtnHubb.setOpaque(false);

        EfectoBoton(jbtnDesf);
        EfectoBoton(jbtnAnt1);
        EfectoBoton(jbtnEins);
        EfectoBoton(jbtnHaw);
        EfectoBoton(jbtnHubb);
        EfectoBoton(jbtnLem);
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabelOvni = new javax.swing.JLabel();
        jbtnHaw = new javax.swing.JButton();
        jbtnLem = new javax.swing.JButton();
        jbtnHubb = new javax.swing.JButton();
        jbtnEins = new javax.swing.JButton();
        jLabelburbuja = new javax.swing.JLabel();
        jbtnDesf = new javax.swing.JButton();
        jbtnAnt1 = new javax.swing.JButton();
        jlabelAstro = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlabelOvni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/QUIZ1.1__1_-removebg-preview.png"))); // NOI18N
        jlabelOvni.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jlabelOvni, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 280, 260));

        jbtnHaw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Hawking.png"))); // NOI18N
        jbtnHaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHawActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHaw, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 280, 230, 240));

        jbtnLem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Lemaitre.png"))); // NOI18N
        jbtnLem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLemActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 230, 230));

        jbtnHubb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Hubble.png"))); // NOI18N
        jbtnHubb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnHubbActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnHubb, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 70, 230, 220));

        jbtnEins.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/A.Einstein.png"))); // NOI18N
        jbtnEins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEinsActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEins, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 70, 230, 230));

        jLabelburbuja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/burbuja3.png"))); // NOI18N
        jLabelburbuja.setText("jLabel1");
        jPanel1.add(jLabelburbuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 350, 240));

        jbtnDesf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonDesaf.png"))); // NOI18N
        jbtnDesf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDesfActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnDesf, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 250, 100));

        jbtnAnt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonAnterior.png"))); // NOI18N
        jbtnAnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnt1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 250, 100));

        jlabelAstro.setText("jLabel1");
        jPanel1.add(jlabelAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, 420));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/btnatras (1).png"))); // NOI18N
        btnVolver.setContentAreaFilled(false);
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 90));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoBigBang3.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -30, 1030, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:
        formulario_TemasAstro pantallaAstro = new formulario_TemasAstro();
        pantallaAstro.setVisible(true);

        // Cerramos la ventana actual de temas
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void jbtnAnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnt1ActionPerformed
        teoriaBigBang1 conexAnt=new teoriaBigBang1();
        conexAnt.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jbtnAnt1ActionPerformed

    private void jbtnDesfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDesfActionPerformed
         Quiz_BingBang1 siguiente = new Quiz_BingBang1();
        siguiente.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jbtnDesfActionPerformed

    private void jbtnEinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEinsActionPerformed
        // TODO add your handling code here:
        reproducirAudioBoton("bbEinst.wav");
    }//GEN-LAST:event_jbtnEinsActionPerformed

    private void jbtnHubbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHubbActionPerformed
        reproducirAudioBoton("bbHubb.wav");
    }//GEN-LAST:event_jbtnHubbActionPerformed

    private void jbtnHawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnHawActionPerformed
        reproducirAudioBoton("bbHaw.wav");
    }//GEN-LAST:event_jbtnHawActionPerformed

    private void jbtnLemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLemActionPerformed
        reproducirAudioBoton("bbLem.wav");
    }//GEN-LAST:event_jbtnLemActionPerformed
    //función para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }    
    
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
    }
    
    public void reproducirNarracion(String archivo) {

        astro.empezarHablar();

        audio.reproducir("/audio/" + archivo, () -> {

            astro.dejarDeHablar();

        });

    }
    
    private void reproducirAudioBoton(String archivo) {

        audio.reproducir("/audio/" + archivo, null);

    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new teoriaBigBang3().setVisible(true);
        } // Variables declaration - do not modify
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JLabel jLabelburbuja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAnt1;
    private javax.swing.JButton jbtnDesf;
    private javax.swing.JButton jbtnEins;
    private javax.swing.JButton jbtnHaw;
    private javax.swing.JButton jbtnHubb;
    private javax.swing.JButton jbtnLem;
    private javax.swing.JLabel jlabelAstro;
    private javax.swing.JLabel jlabelOvni;
    // End of variables declaration//GEN-END:variables
}
