
package Astronomia;


import java.awt.AlphaComposite;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Point;
import java.awt.RenderingHints;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.geom.AffineTransform;
import java.awt.geom.FlatteningPathIterator;
import java.awt.geom.Path2D;
import java.awt.geom.PathIterator;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import javax.swing.Timer;
import javax.swing.plaf.basic.BasicLabelUI;

/**
 *
 * @author User
 */
public class teoriaBigBang2 extends javax.swing.JFrame {
    
    private AstronautaController astro;
    private AudioController audio;
    private float brillo = 0f;
    private boolean aumentando = true;
    
    
    
    public teoriaBigBang2() {
        
        initComponents();
        
        astro = new AstronautaController(jlabelAstro);
        astro.iniciar();        
        
        audio = new AudioController();
        reproducirNarracion("BigBang2.wav");
        //iniciar el programa en el centro de la pantalla
        this.setLocationRelativeTo(this);
        
        
        //ajustar a label
        SetLabel(jLabelMenuPrin, "src/imagen/fondoBigBang2.png");
        
        EfectoBoton(jbtnNex3);
        EfectoBoton(jbtnAnt1);
        
        EfectoLabelMaster(jLabelJup);
        EfectoLabelMaster(jLabelMart);
        EfectoLabelMaster(jLabelSat);
        EfectoLabelMaster(jLabelTie);
        EfectoLabelMaster(jLabelVen);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTie = new javax.swing.JLabel();
        jLabelMart = new javax.swing.JLabel();
        jLabelSat = new javax.swing.JLabel();
        jLabelVen = new javax.swing.JLabel();
        jLabelJup = new javax.swing.JLabel();
        jLabelburbuja = new javax.swing.JLabel();
        jlabelAstro = new javax.swing.JLabel();
        jbtnAnt1 = new javax.swing.JButton();
        jbtnNex3 = new javax.swing.JButton();
        jLabelMenuPrin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ptierra.png"))); // NOI18N
        jLabelTie.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelTie, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 300, 220, 210));

        jLabelMart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelMart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pmarte.png"))); // NOI18N
        jLabelMart.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelMart, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 170, 160));

        jLabelSat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/psaturno.png"))); // NOI18N
        jLabelSat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelSat, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 220, 140));

        jLabelVen.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelVen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pvenus.png"))); // NOI18N
        jLabelVen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 100, 200, 160));

        jLabelJup.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelJup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pjupiter.png"))); // NOI18N
        jLabelJup.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelJup, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 60, 170, 150));

        jLabelburbuja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/burbuja2.png"))); // NOI18N
        jLabelburbuja.setText("jLabel1");
        jPanel1.add(jLabelburbuja, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 350, 240));

        jlabelAstro.setText("jLabel1");
        jPanel1.add(jlabelAstro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 270, 420));

        jbtnAnt1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonAnterior.png"))); // NOI18N
        jbtnAnt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAnt1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnAnt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 510, 250, 100));

        jbtnNex3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/botonNext1.png"))); // NOI18N
        jbtnNex3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnNex3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnNex3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 510, 230, 100));

        jLabelMenuPrin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/fondoBigBang2.png"))); // NOI18N
        jPanel1.add(jLabelMenuPrin, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1030, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAnt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAnt1ActionPerformed
        teoriaBigBang1 conexAnt=new teoriaBigBang1();
        conexAnt.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbtnAnt1ActionPerformed

    private void jbtnNex3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnNex3ActionPerformed
        teoriaBigBang3 conexSig=new teoriaBigBang3();
        conexSig.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jbtnNex3ActionPerformed
     
    //función para ajustar una imagen a un label
    private void SetLabel(JLabel LabelName, String root){
        ImageIcon image = new ImageIcon(root);
        Icon icon = new ImageIcon(image.getImage().getScaledInstance(LabelName.getWidth(), LabelName.getHeight(), Image.SCALE_DEFAULT));
        LabelName.setIcon(icon);
        this.repaint();
    }
    //efecto botón
    private void EfectoBoton(javax.swing.JButton boton) {
            if (boton.getIcon() == null) return;

            ImageIcon imgOriginal = (ImageIcon) boton.getIcon();
            int anchoNormal = imgOriginal.getIconWidth();
            int altoNormal = imgOriginal.getIconHeight();

            // Calculamos las tres escalas:
            int anchoHover = (int) (anchoNormal * 1.02); // Un poco más grande (Hover)
            int altoHover = (int) (altoNormal * 1.02);

            int anchoClick = (int) (anchoNormal * 0.90); // Un poco más chico (Efecto hundido/presionado)
            int altoClick = (int) (altoNormal * 0.90);

            // Creamos los tres iconos escalados
            javax.swing.Icon iconoNormal = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoNormal, altoNormal, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoHover = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoHover, altoHover, java.awt.Image.SCALE_DEFAULT));
            javax.swing.Icon iconoClick = new ImageIcon(imgOriginal.getImage().getScaledInstance(anchoClick, altoClick, java.awt.Image.SCALE_DEFAULT));

            // Estética del botón
            boton.setContentAreaFilled(false);
            boton.setBorderPainted(false);
            boton.setFocusPainted(false);
            boton.setIcon(iconoNormal);

            // Control total de la ilusión de presión
            boton.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoHover); // Crece al pasar el mouse
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoNormal); // Regresa al tamaño base al salir
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                    boton.setIcon(iconoClick); // ¡Se hunde al hacer click!
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                    // Si sueltas el click dentro del botón, vuelve al tamaño hover
                    if (boton.getBounds().contains(e.getPoint())) {
                        boton.setIcon(iconoHover);
                    } else {
                        boton.setIcon(iconoNormal);
                    }
                }
            });
    }
    //
    private static class Destello {
        double x, y;
        double velX, velY;
        float opacidad = 1.0f;
        int tamano;
        Color color;

        Destello(double x, double y, double angulo, java.util.Random random) {
            this.x = x;
            this.y = y;
            // Velocidad aleatoria de disparo
            double velocidad = 1.5 + random.nextDouble() * 2.5; 
            this.velX = Math.cos(angulo) * velocidad;
            this.velY = Math.sin(angulo) * velocidad;
            this.tamano = 2 + random.nextInt(4); 
            this.color = random.nextBoolean() ? Color.WHITE : new Color(180, 100, 255);
        }

        void actualizar() {
            x += velX;
            y += velY;
            opacidad -= 0.04f; // Desvanecimiento
            if (opacidad < 0) opacidad = 0;
        }
    }
    
    private void EfectoLabelMaster(JLabel label) {
        if (label.getIcon() == null || !(label.getIcon() instanceof ImageIcon)) return;

        ImageIcon imgOriginal = (ImageIcon) label.getIcon();
        final int anchoNormal = imgOriginal.getIconWidth();
        final int altoNormal = imgOriginal.getIconHeight();

        // Configuración inicial transparente para el JLabel
        label.setOpaque(false);
        label.setBackground(new java.awt.Color(0, 0, 0, 0));

        final boolean[] mouseEncima = {false};
        final float[] progresoEstrella = {0.0f};
        final java.util.List<Point> puntosContorno = new ArrayList<>();
        final java.util.List<Destello> listaDestellos = new ArrayList<>();
        final Random random = new Random();

        final Timer timerAnimacion = new Timer(16, e -> {
            progresoEstrella[0] += 0.015f;
            if (progresoEstrella[0] > 1.0f) progresoEstrella[0] = 0.0f;

            if (mouseEncima[0] && !puntosContorno.isEmpty()) {
                int totalPuntos = puntosContorno.size();

                // Generar destellos controlados en el contorno
                for (int k = 0; k < 60; k++) { // Bajado a 3 para evitar saturación visual en los planetas
                    int indiceAleatorio = random.nextInt(totalPuntos);
                    Point p = puntosContorno.get(indiceAleatorio);

                    double centroX = label.getWidth() / 2.0;
                    double centroY = label.getHeight() / 2.0;
                    double anguloDisparo = Math.atan2(p.y - centroY, p.x - centroX);
                    anguloDisparo += (random.nextDouble() - 0.5) * 0.5;

                    listaDestellos.add(new Destello(p.x, p.y, anguloDisparo, random));
                }
            }

            Iterator<Destello> iter = listaDestellos.iterator();
            while (iter.hasNext()) {
                Destello d = iter.next();
                d.actualizar();
                if (d.opacidad <= 0) {
                    iter.remove();
                }
            }

            label.repaint();
        });

        // Cambiado a BasicLabelUI para que funcione nativamente en JLabels
        label.setUI(new BasicLabelUI() {
            @Override
            public void paint(Graphics g, javax.swing.JComponent c) {
                Graphics2D g2d = (Graphics2D) g.create();
                g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

                // 1. RENDERIZAR LOS DESTELLOS ILUMINADOS ATRÁS O ALREDEDOR
                for (Destello d : listaDestellos) {
                    g2d.setComposite(AlphaComposite.getInstance(AlphaComposite.SRC_OVER, d.opacidad));
                    g2d.setColor(d.color);
                    g2d.fillOval((int) d.x - d.tamano/2, (int) d.y - d.tamano/2, d.tamano, d.tamano);
                }
                g2d.setComposite(AlphaComposite.SrcOver); 

                // 2. RENDERIZAR LA ESTRELLA GUÍA EN EL CONTORNO
                if (mouseEncima[0] && !puntosContorno.isEmpty()) {
                    int totalPuntos = puntosContorno.size();
                    int indiceActual = (int) (progresoEstrella[0] * (totalPuntos - 1));
                    Point puntoEstrella = puntosContorno.get(indiceActual);

                    AffineTransform oldTransform = g2d.getTransform();

                    g2d.translate(puntoEstrella.x, puntoEstrella.y);
                    g2d.rotate(progresoEstrella[0] * Math.PI * 6);
                    g2d.setColor(new Color(255, 215, 0));

                    Path2D estrellaPath = new Path2D.Double();
                    double rExter = 5.5; 
                    double rInter = 2.2; 
                    estrellaPath.moveTo(0, -rExter);
                    for (int i = 1; i < 50; i++) { // Corregido el límite a 10 para una estrella de 5 puntas estándar
                        double r = (i % 2 == 0) ? rExter : rInter;
                        double angulo = i * Math.PI / 5.0;
                        estrellaPath.lineTo(r * Math.sin(angulo), -r * Math.cos(angulo));
                    }
                    estrellaPath.closePath();
                    g2d.fill(estrellaPath);

                    g2d.setTransform(oldTransform);
                }

                g2d.dispose();

                // 3. PINTAR LA IMAGEN ORIGINAL DEL PLANETA POR ENCIMA
                super.paint(g, c); 
            }
        });

        label.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                mouseEncima[0] = true;

                if (puntosContorno.isEmpty()) {
                    // Generar el mapa del contorno basado en el tamaño físico real del Icon
                    BufferedImage bi = new BufferedImage(anchoNormal, altoNormal, BufferedImage.TYPE_INT_ARGB);
                    Graphics g = bi.createGraphics();
                    imgOriginal.paintIcon(label, g, 0, 0);
                    g.dispose();

                    Path2D mapaPixeles = new Path2D.Float();
                    boolean trazando = false;

                    // Desfase de centrado si el JLabel es más grande que la imagen interna
                    int offsetX = (label.getWidth() - anchoNormal) / 2;
                    int offsetY = (label.getHeight() - altoNormal) / 2;

                    for (int y = 0; y < altoNormal; y++) {
                        for (int x = 0; x < anchoNormal; x++) {
                            int alpha = (bi.getRGB(x, y) >> 24) & 0xff;
                            if (alpha > 40) { // Detecta los bordes transparentes del planeta PNG
                                int targetX = x + offsetX;
                                int targetY = y + offsetY;
                                if (!trazando) {
                                    mapaPixeles.moveTo(targetX, targetY);
                                    trazando = true;
                                } else {
                                    mapaPixeles.lineTo(targetX, targetY);
                                }
                            }
                        }
                    }
                    mapaPixeles.closePath();

                    FlatteningPathIterator iter = new FlatteningPathIterator(mapaPixeles.getPathIterator(null), 1.0);
                    float[] coords = new float[6];
                    while (!iter.isDone()) {
                        int tipo = iter.currentSegment(coords);
                        if (tipo == PathIterator.SEG_MOVETO || tipo == PathIterator.SEG_LINETO) {
                            puntosContorno.add(new Point((int) coords[0], (int) coords[1]));
                        }
                        iter.next();
                    }
                }

                timerAnimacion.start();
            }

            @Override
            public void mouseExited(MouseEvent e) {
                mouseEncima[0] = false;
                Timer retrasoApagado = new Timer(5000, ev -> {
                    if (!mouseEncima[0] && listaDestellos.isEmpty()) {
                        timerAnimacion.stop();
                    }
                });
                retrasoApagado.setRepeats(false);
                retrasoApagado.start();
            }
        });
    }
    
    public void reproducirNarracion(String archivo) {

        astro.empezarHablar();

        audio.reproducir("/audio/" + archivo, () -> {

            astro.dejarDeHablar();

        });

    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teoriaBigBang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new teoriaBigBang2().setVisible(true);
        } // Variables declaration - do not modify
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelJup;
    private javax.swing.JLabel jLabelMart;
    private javax.swing.JLabel jLabelMenuPrin;
    private javax.swing.JLabel jLabelSat;
    private javax.swing.JLabel jLabelTie;
    private javax.swing.JLabel jLabelVen;
    private javax.swing.JLabel jLabelburbuja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnAnt1;
    private javax.swing.JButton jbtnNex3;
    private javax.swing.JLabel jlabelAstro;
    // End of variables declaration//GEN-END:variables
}
